### PR TITLE
Download Android validation layers from github release site. 

### LINKED ISSUE #571: Pull Android validation layers from Validation Layer github instead of NDK
Android Validation layers have been removed from NDK:
   https://github.com/android/ndk/issues/1374
Android build still refers to the non-existing NDK directory.

### PR DESCRIPTION
**Pull request by ggfan**
NDK stops packing layer library for a while: this is needed before updating to ndk-r25.

Fixes #571

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Review by tomadamatkinson — DISMISSED** [review]
LGTM
Unable to test locally at the moment
I'll take a look into the CI

**Review by JoseEmilio-ARM — DISMISSED** [review]
Great contribution, thanks!

**Comment by ggfan** [comment]
May you kindly take a look again (rebased the pull request)? thank you!

**Comment by ggfan** [comment]
The following CI errors do not seem to be related to this Pull Request:
```
Error while processing /__w/Vulkan-Samples/Vulkan-Samples/framework/spirv_reflection.cpp.
/usr/bin/clang-tidy -header-filter=framework,samples,vulkan_samples -checks=-*,google-*,-google-runtime-references -p=build/clang -quiet /__w/Vulkan-Samples/Vulkan-Samples/framework/spirv_reflection.cpp
/__w/Vulkan-Samples/Vulkan-Samples/third_party/spirv-cross/spirv_common.hpp:539:19: error: unqualified call to 'std::move' [clang-diagnostic-unqualified-std-cast-call]
            : expression(move(expr))
                         ^
                         std::
/__w/Vulkan-Samples/Vulkan-Samples/third_party/spirv-cross/spirv_glsl.hpp:141:17: error: unqualified call to 'std::move' [clang-diagnostic-unqualified-std-cast-call]
            : Compiler(move(spirv_))
                       ^
                       std::
```

**Review by SaschaWillems — DISMISSED** [review]
Compiles fine for me. The layer is downloaded and added to the apk as expected. So LGTM.

**Review by JoseEmilio-ARM — DISMISSED** [review]

**Review by tomadamatkinson — DISMISSED** [review]

**Review by gpx1000 — DISMISSED** [review]

**Comment by marty-johnson59** [comment]
Hi @ggfan, looks like this branch has conflicts that need resolving before I can merge.  Can you take a look?  Thanks.

**Comment by ggfan** [comment]
Yeah, need to rebase with the other PullRequest (as it is in now).  Just done that, but it need to be re-approved.  @SaschaWillems @JoseEmilio-ARM @tomadamatkinson @gpx1000 , may you kindly lend an approval again?  thank you so much!

**Review by gpx1000 — APPROVED** [review]

**Comment by marty-johnson59** [comment]
Thanks, I'll waive all the re-approvals given this is just a rebase.  I'll merge shortly once all the checks are complete - stay tuned

**Comment by ggfan** [comment]
Thank you, @marty-johnson59 !

**Comment by ouclbc** [comment]
Exception is:
Caused by: java.net.SocketTimeoutException: Read timed out
	at download_vvl_bsbp0dw2v0d3oahmiwqybkc0w$_run_closure1.doCall(D:\work2023\Vulkan\Vulkan-Samples\build\android_gradle\app\download_vvl.gradle:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:73)
	at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
	at org.gradle.util.internal.ConfigureUtil.configureSelf(ConfigureUtil.java:131)
	at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:666)
	at org.gradle.api.DefaultTask.configure(DefaultTask.java:309)
	at org.gradle.api.internal.project.DefaultProject.task(DefaultProject.java:1276)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:484)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:196)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
	at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:135)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:84)
	at download_vvl_bsbp0dw2v0d3oahmiwqybkc0w.run(D:\work2023\Vulkan\Vulkan-Samples\build\android_gradle\app\download_vvl.gradle:51)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 201 more

**Pull request merged**
