### PR TITLE
Change vkb::core::HPPVulkanResource from a facade over vkb::core::VulkanResource to a self-contained class using vulkan.hpp

### PR DESCRIPTION
**Pull request by asuessenbach**
## Description

Transcoding this part of the framework completes the minimal set of classes to initialize the framework using Vulkan-Hpp.

I have tested it on Window10 on nvidia HW.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

### CODE REVIEW

**Comment by asuessenbach** [comment]
Does anyone like to review this?

**Comment by SaschaWillems** [comment]
Will try to review this asap :)

**Review by SaschaWillems — APPROVED** [review]
LGTM. Compiles and works fine on Windows 10 with an NV RTX 2060.

**Review by gpx1000 — APPROVED** [review]

**Review by TomAtkinsonArm — APPROVED** [review]
LGTM

**Comment by TomAtkinsonArm** [comment]
@marty-johnson59 this one has three approvals :)

**Comment by asuessenbach** [comment]
As asked before (#442, for example) but did not get a definitive answer: may I just merge this PR as it has three approvals (and all checks have passed, of course)?

**Comment by marty-johnson59** [comment]
Yep, that's fine.  I'll merge now..

**Pull request merged**
