### PR TITLE
set prepared flag to true to enable resize

### LINKED ISSUE #377: Validation errors and crash in Buffer device address, Descriptor indexing, Timeline semaphore
**Linux Nvidia driver 470.74**

On resize every of listed Samples Window become black(no image) and application not respond (freeze/crash).

**Buffer device address** `vulkan_samples sample buffer_device_address` - launch with no crash, but two Validation errors:
```
VUID-VkShaderModuleCreateInfo-pCode-04147(ERROR / SPEC): msgNum: 1028204675 - Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-04147 ] Object 0: handle = 0x353ec08, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x3d492883 | vkCreateShaderModule(): The SPIR-V Extension (SPV_EXT_physical_storage_buffer) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the SPIR-V extensions listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.2.170.0/linux/1.2-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-04147)
    Objects: 1
        [0] 0x353ec08, type: 3, name: NULL
VUID-VkShaderModuleCreateInfo-pCode-04147(ERROR / SPEC): msgNum: 1028204675 - Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-04147 ] Object 0: handle = 0x353ec08, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x3d492883 | vkCreateShaderModule(): The SPIR-V Extension (SPV_EXT_physical_storage_buffer) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the SPIR-V extensions listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.2.170.0/linux/1.2-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-04147)
    Objects: 1
        [0] 0x353ec08, type: 3, name: NULL
```

**Crash on resize**:
```
VUID-vkQueueSubmit-pWaitSemaphores-00069(ERROR / SPEC): msgNum: -276461468 - Validation Error: [ VUID-vkQueueSubmit-pWaitSemaphores-00069 ] Object 0: handle = 0x130000000013, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0x3405438, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xef858864 | vkQueueSubmit(): pSubmits[0].pWaitSemaphores[0] Queue VkQueue 0x3405438[] is waiting on semaphore (VkSemaphore 0x130000000013[]) that has no way to be signaled. The Vulkan spec states: All elements of the pWaitSemaphores member of all elements of pSubmits must be semaphores that are signaled, or have semaphore signal operations previously submitted for execution (https://vulkan.lunarg.com/doc/view/1.2.170.0/linux/1.2-extensions/vkspec.html#VUID-vkQueueSubmit-pWaitSemaphores-00069)
    Objects: 2
        [0] 0x130000000013, type: 5, name: NULL
        [1] 0x3405438, type: 4, name: NULL
```

**Descriptor indexing** `vulkan_samples sample descriptor_indexing` - launch with no crash and no Validation errors.
On **resize crash** with same Validation error error.`vkQueueSubmit-pWaitSemaphores`

**Timeline semaphore** - on resize it crash/freeze, no Validation errors.

### PR DESCRIPTION
**Pull request by gpx1000**
## Description

Prepared is not currently set to true when the sample is prepared essentially making window operations not do the right thing.

Fixes #377 
## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Review by SaschaWillems — APPROVED** [review]
LGTM

**Review by JoseEmilio-ARM — APPROVED** [review]

**Comment by TomAtkinsonArm** [comment]
@marty-johnson59 small change, added Gary for a third vendors approval but this also LGTM :+1:

**Review by gary-sweet — APPROVED** [review]
Changes look fine, but our platform doesn't allow resize, so I can't test that it actually does anything.

**Comment by marty-johnson59** [comment]
Merging w/ 3 approvals.  LMK if issues.

**Pull request merged**
