### PR TITLE
WIP: Fix crash on android when trying to log into file

### PR DESCRIPTION
**Pull request by ylz-at**
## Description

Using `android_sink_mt` for android sinks.
If `stdout_color_sink_mt` is used, spdlog will try to write to `storage/emulated/0/com.khronos.vulkan_samples/output/[date].txt` . Spdlog fail to open the file and `throw spdlog_ex("Failed opening file " + os::filename_to_str(_filename) + " for writing", errno);`.

Apparently, spdlog_ex is not handled and leads to a crash.

Crashed on `Samsumg S10` with Android 11(OneUI) installed.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by TomAtkinsonArm** [comment]
@ylz-at correct idea, but wrong place. See https://github.com/KhronosGroup/Vulkan-Samples/blob/ee6c1522af8ba9b56f8416c2eedafb440f681085/framework/platform/android/android_platform.cpp#L521

This is where the android platform initializes its logger. We could remove the file logger or place an ifdef around it

**Comment by ylz-at** [comment]
@TomAtkinsonArm I think the correct solution is to use a path with permissions.

So we have to make some changes here, so then we can keep the ability to log into files.

```java
            File external_files_dir = getExternalFilesDir("");
            File temp_files_dir = getCacheDir();
            if (external_files_dir != null && temp_files_dir != null) {
                // User no longer has permissions to access applications' storage, save files in
                // top level (shared) external storage directory
                String shared_storage = external_files_dir.getPath().split(Pattern.quote("Android"))[0];
                external_files_dir = new File(shared_storage, getPackageName());
                initFilePath(external_files_dir.toString(), temp_files_dir.toString());
            }
```

According to the android developer doc, https://developer.android.com/about/versions/11/privacy/storage#app-specific-external
> Starting in Android 11, apps cannot create their own [app-specific directory on external storage](https://developer.android.com/training/data-storage/app-specific#external). To access the directory that the system provides for your app, call [getExternalFilesDirs()](https://developer.android.com/reference/android/content/Context#getExternalFilesDirs(java.lang.String)).

I will update the `getExternalFilesDir` part this weekend.

**Comment by TomAtkinsonArm** [comment]
Hey @ylz-at, are there any further changes to this PR?

**Comment by SaschaWillems** [comment]
@marty-johnson59 : I think we should close this. There hasn't been any reaction from the OP in over a year.

**Comment by marty-johnson59** [comment]
Sounds good.  Let's close this - but please re-open if there are further changes needed.  Thanks!

**Pull request closed without merging**
