### PR TITLE
Fix small typo in multi_draw_indirect sample

### LINKED ISSUE #449: Small typo in MultiDrawIndirect sample
## Background
The member variable `m_enable_mci` is misspelt; it should be `m_enable_mdi`, as this refers to whether "**M**ulti**D**raw**I**ndirect" is enabled, and to fit with the other variable `m_supports_mdi`.

### PR DESCRIPTION
**Pull request by kanerogers**
## Description
Fixes a typo in the multi_draw_indirect sample.

Closes #449 

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by TomAtkinsonArm** [comment]
Approved CI usage

**Review by TomAtkinsonArm — CHANGES_REQUESTED** [review]
LGTM - Requires clang format fixes

**Comment by kanerogers** [comment]
> LGTM - Requires clang format fixes

Hrm, musn't have set up my `clang format` correctly. Will get this fixed today - thank you!

**Review by TomAtkinsonArm — DISMISSED** [review]
LGTM

**Comment by TomAtkinsonArm** [comment]
Ah one more pipeline, Copyright headers needs to be `2021-2022` in the files that have changed

**Comment by kanerogers** [comment]
@TomAtkinsonArm This should be done now! 🤞🏻

**Review by gpx1000 — APPROVED** [review]

**Review by TomAtkinsonArm — APPROVED** [review]

**Comment by TomAtkinsonArm** [comment]
@marty-johnson59 tiny spelling fix - this can be merged at your discretion :)

**Pull request merged**
