### PR TITLE
Alternative fix for invalid move constructors

### PR DESCRIPTION
**Pull request by jherico**
## Description

This is an alternative fix for #36.  Unlike the other fix in #40, this does not attempt to create valid move contructors for `SemaphorePool`, `FencePool`, `RenderTarget` and `RenderFrame`.  Instead it changes the move constructors for all of them from `= default` to `= delete`, and changes the `RenderContext` class to encapsulate frames in a `std::vector<std::unique_ptr<RenderFrame>>` instead of a ``std::vector<RenderFrame>`

## General Checklist:

Please ensure the following points are checked:

- [X] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [X] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [X] I have commented any added functions (in line with Doxygen)
- [X] I have commented any code that could be hard to understand
- [X] My changes do not add any new compiler warnings
- [X] My changes do not add any new validation layer errors or warnings
- [X] I have used existing framework/helper functions where possible
- [X] My changes build and run on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)

### CODE REVIEW

**Comment by ZandroFargnoli** [comment]
@jherico what was the reason for closing this? I believe the changes here are more preferable and inline with our architecture and how we handle things of similar nature.

**Comment by ZandroFargnoli** [comment]
Can we reopen?

**Comment by jherico** [comment]
Sure...  I just didn't think the architectural changes would fly, and it was failing the CI tests, so I closed it.  However, I've fixed the one missing copyright change header, and also created a new commit to fix the doxygen failure (which appears to be completely unrelated to my changes)

**Review by gary-sweet — APPROVED** [review]
Works ok for Broadcom

**Review by ZandroFargnoli — APPROVED** [review]
The changes work for Arm! LGTM

**Comment by ZandroFargnoli** [comment]
Please refer to https://github.com/KhronosGroup/Vulkan-Samples/issues/29 to see the reason for why this was closed.

**Review by aurolou — APPROVED** [review]

**Pull request merged**
