### PR TITLE
Add new sample for fragment shading rate (VK_KHR_fragment_shading_rate)

### PR DESCRIPTION
**Pull request by SaschaWillems**
## Description

**This is a provisional PR for people to take a look at and give feedback. The sample itself is pretty much finished, but validation layers aren't 100% ready yet, and it also requires some other PRs to be merged first. So please don't merge yet**

This PR adds a sample for the recently released VK_KHR_fragment_shading_rate extension, which provides a flexible technique to control the fragment shading rate. This allows e.g. for increasing the number of pixels covered by a fragment shader invocation. This is something that can be used e.g. increase performance for foveated rendering, where only the pixels right in front of the viewer need to be sampled with a 1:1: coverage.

The sample makes use of a special attachment, storing fragment shading rates. This attachment is then consumed by the render pass to control fragment shader invocations per pixel while rendering the scene. It implements a circular fragment shading rate pattern, with 1:1 invocations in the center, lowering the number outwards.

I have tested the sample on recent NVIDIA Vulkan developer drivers on Windows 10.

It currently also includes all required submodule updates, so it should compile out of the box.

fragment_shading_rate

The Vulkan docs task list for the extension can be found [here](https://github.com/KhronosGroup/Vulkan-Docs/issues/1384).

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [n/a] My changes do not add any new validation layer errors or warnings (Validation layers not ready yet)
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [n/a] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [n/a] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Review by gary-sweet — COMMENTED** [review]
Correctly reports as unsupported by Broadcom (after hacking around the python3 issue in glslang).

**Comment by marty-johnson59** [comment]
Per discussion on the 11/23 call, we really just need reviews/approvals by the DT vendors as this is DT specific (and make sure it doesn't break on mobile).  @mattruschnv, @aurolou, can you please review/approve so we can merge at the next meeting?  Thanks!

**Comment by marty-johnson59** [comment]
Another ping for reviews on this one.  @mattruschnv, @aurolou, any chance you can get to this so we can merge after Monday's meeting? thx

**Review by aurolou — CHANGES_REQUESTED** [review]
This sample seems to wrongly query the entry point, it improperly uses vkGetDeviceProc address with the instance instead of the device. Could this get fixed, please? :)

**Comment by SaschaWillems** [comment]
@aurolou: Thanks for the hint. As all other samples, this sample does not get the entry points by itself as we are using Volk as a dynamic loader. Does this apply to all entry points for the VK_KHR_fragment_shading_rate related functions? If so, this may be an error in Volk.

**Comment by SaschaWillems** [comment]
Can someone with an AMD GPU please test this? The sample works fine for me on NVIDIA, and I can't find out why this fails on AMD.

**Comment by AaronHaganAMD** [comment]
This works on my AMD GPU .. I say ship it !

**Comment by SaschaWillems** [comment]
Thanks a lot for testing and confirming this on AMD hardware 👍

**Pull request merged**
