### PR TITLE
Add timeline semaphore sample

### PR DESCRIPTION
**Pull request by HansKristian-Work**
## Description

Implements a sample demonstrating all the major use cases for timeline semaphores.

Since this is rather abstract to visualize I went with an esoteric way of implementing a "Game of Life" simulation.

Adds some common framework entry points which fixes some issues I ran into while implementing the sample. The major issue was using vkDeviceWaitIdle() after each frame (why?!), which I had to replace with vkQueueWaitIdle. Some other thing was better queries if we could use async compute or not. This is important since otherwise we cannot demonstrate proper out of order submit.

I also had to add some support for concurrent shared images to vkb::core::Image.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

I tested on RADV, Arm Mali, AMDGPU-PRO, NVIDIA Linux. I also tested with single queue.

### CODE REVIEW

**Review by gary-sweet — DISMISSED** [review]

**Comment by SaschaWillems** [comment]
I can't approve, but this LGTM and works as expected on my NVIDIA RTX 2060 (Windows 10).

I do have very minor suggestion for the accompanying tutorial though: The code blocks should be marked with cpp, so proper language syntax highlighting will be used by using ´´´cpp instead of ```

**Comment by SaschaWillems** [comment]
This sample locks up on my NVIDIA RTX 2060. I can see a first frame, but after that it seems to get stuck and I have to to forcefully kill the application. Running this from VS2019 locks up the sample in such a way that I can't even close the sample with the task manager. I didn't get any validation layer messages, so I'm not sure why this hang occurs.

**Comment by HansKristian-Work** [comment]
> This sample locks up on my NVIDIA RTX 2060. I can see a first frame, but after that it seems to get stuck and I have to to forcefully kill the application. Running this from VS2019 locks up the sample in such a way that I can't even close the sample with the task manager. I didn't get any validation layer messages, so I'm not sure why this hang occurs.

That is surprising.

**Comment by SaschaWillems** [comment]
That was my first reaction too. Actually I had to power-cycle my PC. I'll try to test this again before the next call so make sure that this wasn't a one-time problem.

**Comment by HansKristian-Work** [comment]
I'll try to repro myself soon.

**Comment by HansKristian-Work** [comment]
@SaschaWillems The sample works fine on AMDGPU-PRO as well as RTX 3070 on Linux, but I also get a system lockup on Windows with 3070 for some reason. Both OSes using latest beta driver.

It seems to hang in vkQueuePresentKHR for whatever reason, and the process hangs so hard that the process in unkillable, so it might have deadlocked inside the kernel. A system restart never completes, and I have to forcefully reboot with a power cycle. This kind of system instability must be a driver bug I think.

**Comment by HansKristian-Work** [comment]
There is this VUID actually (but validation layers don't catch it):

>  All elements of the pWaitSemaphores member of pPresentInfo must reference a semaphore signal operation that has been submitted for execution and any semaphore signal operations on which it depends (if any) **must have also been submitted for execution**

So that could explain it, need to investigate a bit more ...

**Comment by HansKristian-Work** [comment]
So, did some more digging and the sample also breaks on AMD Windows (yet also works on Linux, mysterious!)

I tried ensuring that the VUID for binary semaphore signal dependencies were met, but that did not help.

The only thing that does help is to not use out-of-order signalling at all. I'm a bit puzzled about this. It works just fine on Linux and Android drivers.

**Comment by SaschaWillems** [comment]
Maybe it's worth a ticket to AMD and NVIDIA? No matter of how the usage case looks, a kernel deadlock should never occur.

**Comment by HansKristian-Work** [comment]
Contacted both.

**Comment by HansKristian-Work** [comment]
I added some more wording to handle the binary semaphore issue, but it still hangs. Both IHVs are aware of the problem now.

**Comment by SaschaWillems** [comment]
I can confirm that the sample is no longer added to the project on windows.

But maybe we should also add somethin to the samples' source too for people that try to compile this manually on Windows? Maybe a simple #error pre-processor instruction to make it fail on Win32?

**Comment by HansKristian-Work** [comment]
How would you build the sample manually when it doesn't even exist in the CMakeLists on WIN32 in this case?

**Comment by SaschaWillems** [comment]
You could add it to the Visual Studio solution by hand. But then again you'd have to add the entry point to the sample's project file, so it's very unlikely, Rethinking this, it really doesn't make sense to add such a pre processor define.

**Comment by marty-johnson59** [comment]
@HansKristian-Work, let's resolve the conflicts on this one too.  LMK when this is ready - I'll ping folks for reviews.

**Comment by HansKristian-Work** [comment]
@marty-johnson59 Resolved.

**Comment by marty-johnson59** [comment]
@r-potter, @AlejandroCosin , @carlosadcq, @SaschaWillems, @gary-sweet, we're looking for reviews/approvals for this sample - it's currently only supported on mobile until some issues are resolved, so hoping you guys can check it out/approve.  Thanks!

**Review by gpx1000 — DISMISSED** [review]
LGTM; worked well on Linux.

**Review by gpx1000 — DISMISSED** [review]

**Comment by marty-johnson59** [comment]
@r-potter, @AlejandroCosin , @carlosadcq, @SaschaWillems, @gary-sweet, still looking for a couple more approvals - especially from mobile folks.  Thanks!

**Review by gary-sweet — DISMISSED** [review]

**Review by r-potter — CHANGES_REQUESTED** [review]
Unfortunately this crashes on my Mali Note10 without writing anything useful to the log. I'll continue investigating and update if I find anything useful 

````
2021-03-03 11:30:11.352 30599-31436/? W/.vulkan_sample: 0xebadde09 skipped times: 0
    
    --------- beginning of crash
2021-03-03 11:30:11.352 30599-31436/? A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 31436 (Thread-6), pid 30599 (.vulkan_samples)
2021-03-03 11:30:11.361 5532-5532/? I/Layer: id=7009[1] Destroyed Surface(name=2a09afd com.khronos.vulkan_samples/com.khronos.vulkan_samples.NativeSampleActivity)/@0xe002efa - animation-leash#0
2021-03-03 11:30:11.388 31445-31445/? A/DEBUG: pid: 30599, tid: 31436, name: Thread-6  >>> com.khronos.vulkan_samples <<<
2021-03-03 11:30:11.390 31445-31445/? A/DEBUG:       #00 pc 000000000023c67c  /data/app/com.khronos.vulkan_samples-QGyWd4ZkVi-rZvfJfF5FIw==/lib/arm64/libvulkan_samples.so (vkb::Device::get_handle() const) (BuildId: c0166e04b076993c540f7fb42e73f09da88ad0dd)
2021-03-03 11:30:11.390 31445-31445/? A/DEBUG:       #01 pc 0000000000366634  /data/app/com.khronos.vulkan_samples-QGyWd4ZkVi-rZvfJfF5FIw==/lib/arm64/libvulkan_samples.so (TimelineSemaphore::wait_timeline_cpu(TimelineSemaphore::Timeline const&)+84) (BuildId: c0166e04b076993c540f7fb42e73f09da88ad0dd)
2021-03-03 11:30:11.390 31445-31445/? A/DEBUG:       #02 pc 0000000000366590  /data/app/com.khronos.vulkan_samples-QGyWd4ZkVi-rZvfJfF5FIw==/lib/arm64/libvulkan_samples.so (TimelineSemaphore::finish()+24) (BuildId: c0166e04b076993c540f7fb42e73f09da88ad0dd)
2021-03-03 11:30:11.390 31445-31445/? A/DEBUG:       #03 pc 0000000000210884  /data/app/com.khronos.vulkan_samples-QGyWd4ZkVi-rZvfJfF5FIw==/lib/arm64/libvulkan_samples.so (vkb::VulkanSamples::finish()+32) (BuildId: c0166e04b076993c540f7fb42e73f09da88ad0dd)
2021-03-03 11:30:11.390 31445-31445/? A/DEBUG:       #04 pc 0000000000216b94  /data/app/com.khronos.vulkan_samples-QGyWd4ZkVi-rZvfJfF5FIw==/lib/arm64/libvulkan_samples.so (vkb::Platform::terminate(vkb::ExitCode)+32) (BuildId: c0166e04b076993c540f7fb42e73f09da88ad0dd)
2021-03-03 11:30:11.391 31445-31445/? A/DEBUG:       #05 pc 0000000000282700  /data/app/com.khronos.vulkan_samples-QGyWd4ZkVi-rZvfJfF5FIw==/lib/arm64/libvulkan_samples.so (vkb::AndroidPlatform::terminate(vkb::ExitCode)+336) (BuildId: c0166e04b076993c540f7fb42e73f09da88ad0dd)
2021-03-03 11:30:11.391 31445-31445/? A/DEBUG:       #06 pc 00000000001ed1bc  /data/app/com.khronos.vulkan_samples-QGyWd4ZkVi-rZvfJfF5FIw==/lib/arm64/libvulkan_samples.so (android_main+612) (BuildId: c0166e04b076993c540f7fb42e73f09da88ad0dd)
2021-03-03 11:30:11.391 31445-31445/? A/DEBUG:       #07 pc 00000000005fdf14  /data/app/com.khronos.vulkan_samples-QGyWd4ZkVi-rZvfJfF5FIw==/lib/arm64/libvulkan_samples.so (BuildId: c0166e04b076993c540f7fb42e73f09da88ad0dd)
````

**Comment by HansKristian-Work** [comment]
@r-potter Is timeline semaphore supported on that driver? It works just fine for me on an S20 Exynos with r26 driver.
It might be as simple as them not being supported, and something going wrong when it tears down on startup ...

**Comment by r-potter** [comment]
> @r-potter Is timeline semaphore supported on that driver? It works just fine for me on an S20 Exynos with r26 driver.
> It might be as simple as them not being supported, and something going wrong when it tears down on startup ...

I'm still investigating, but this seems to be correct. The device doesn't support the extension. A debug build therefore throws an "extension not found" exception during device creation. Somehow the release build seems to be executing the teardown code, which assumes everything was correctly initialized.

**Comment by HansKristian-Work** [comment]
Ok, I'll try to repro this on my S9.

**Comment by HansKristian-Work** [comment]
Resolved, was just framework calling ::finish() on a null device, which was unexpected, but I just guard against that now.

**Review by r-potter — APPROVED** [review]
Approving in so far as I can. 

Han-Kristian's latest fix appears to resolve the hard crash when the extension is not present. 

For Samsung devices the sample requires an S20 with up to date drivers (which I don't have immediate access to), but after discussing with Hans-Kristian I'm happy to approve regardless.

**Comment by HansKristian-Work** [comment]
@marty-johnson59 We have three approvals now. Good to go.

**Pull request merged**
