### PR TITLE
Implemented a simpler way for samples to request features

### PR DESCRIPTION
**Pull request by ZandroFargnoli**
## Description

This PR provides a cleaner solution to GPU extension features.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build and run on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)

### CODE REVIEW

**Comment by ZandroFargnoli** [comment]
Rebased on @gary-sweet 's stats work, so it shouldn't be merged until his work is in master

**Review by gary-sweet — DISMISSED** [review]
LGTM

**Comment by ZandroFargnoli** [comment]
@gary-sweet + others: This is now based on master again so it can be reviewed more easily, when a PR goes into master it should be the responsibility of the pending PRs to then rebase

Having said this I don't mind holding this off and rebasing once Garys PR is complete

**Comment by gary-sweet** [comment]
> When a PR goes into master it should be the responsibility of the pending PRs to then rebase

That's true, but if we know in advance that such actions will cause non-trivial rebases, it seems rather fruitless to ignore that. This seems to be more an issue with the way that github presents the changes in stacked PRs than an issue with stacked PRs as such.

> Having said this I don't mind holding this off and rebasing once Garys PR is complete

Thanks

**Comment by JoseEmilio-ARM** [comment]
Just noticed this build warning, worth checking it isn't there with this change after the rebase:
```
In file included from /Vulkan-Samples/app/vulkan_samples.h:23:
In file included from /Vulkan-Samples/build/mac/app/samples.h:37:
/Vulkan-Samples/app/../samples/extensions/raytracing_basic/raytracing_basic.h:105:15: warning: 'request_gpu_features'
      overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
        void         request_gpu_features(vkb::PhysicalDevice &gpu);
                     ^
/Vulkan-Samples/framework/vulkan_sample.h:253:15: note: overridden virtual function is here
        virtual void request_gpu_features(PhysicalDevice &gpu);
                     ^
1 warning generated.
```

**Comment by ZandroFargnoli** [comment]
@JoseEmilio-ARM This build warning should exist inside `master` and is not related to this PR. Sascha and the people reviewing his PR must of missed this. I will push a fix now for this.

**Comment by SaschaWillems** [comment]
Yeah, I noticed this one too, but I'm not sure if it was there when I made the initial PR.

**Review by gary-sweet — DISMISSED** [review]

**Review by aurolou — DISMISSED** [review]

**Review by aurolou — APPROVED** [review]

**Review by r-potter — APPROVED** [review]
LGTM

**Review by AlejandroCosin — APPROVED** [review]

**Pull request merged**
