### PR TITLE
Add Float16 arithmetic performance sample

### PR DESCRIPTION
**Pull request by HansKristian-Work**
## Description

Adds a 16-bit arithmetic performance sample using Float16 feature of VK_KHR_float16_int8.
Also demonstrates use of 16-bit push constants as well as 16-bit SSBO.

The sample brute forces a lot of 16-bit arithmetic workload and shows uplift on devices which can take advantage of packed 16-bit operations.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

Tested build on Linux/Android. The sample does not touch common code, so no Doxygen is added.

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

Samples are tested on NV (Linux), RADV and Arm Mali.

### CODE REVIEW

**Review by wasimabbas-arm — DISMISSED** [review]

**Comment by HansKristian-Work** [comment]
@wasimabbas-arm Fixed clang formatting check, please re-approve.

**Review by wasimabbas-arm — DISMISSED** [review]

**Review by gary-sweet — COMMENTED** [review]
Correctly reports unsupported for Broadcom.
I'll leave the approvals to those that can actually test the new functionality.

**Comment by marty-johnson59** [comment]
Hi Team, per discussion this week, this one looks ready.  Can we get 3 reviews/approvals so we can merge. Thanks!

@r-potter, @aurolou, @Benjamin-Mitchell, @ZandroFargnoli , @mattruschnv, @AlejandroCosin, @carlosadcq

**Review by aurolou — CHANGES_REQUESTED** [review]
Hi, this sample also requires storagePushConstant16 Feature, which is unfortunately not supported on AMD. Is it possible to implement a fallback path, as this sample also demonstrates the use of other features?

**Comment by HansKristian-Work** [comment]
> Hi, this sample also requires storagePushConstant16 Feature, which is unfortunately not supported on AMD. Is it possible to implement a fallback path, as this sample also demonstrates the use of other features?

RADV supports it fine, why not the proprietary driver?

What is required to get this approved then? Remove requirement of PushConstant16 for both off and on paths and have 4 total shader variants (Off + Push16, Off, On + Push16, On)? The easiest is to just not use Push16 in the off path.

**Comment by HansKristian-Work** [comment]
Ok, I added a fallback path for when PushConstant16 is not supported.

**Review by aurolou — DISMISSED** [review]

**Comment by aurolou** [comment]
perfect, thank you so much :)

**Review by r-potter — CHANGES_REQUESTED** [review]
Tested on Note 10 (Mali+Adreno) and S20 Mali.

Sample works fine on Mali. Fails on Adreno due to the lack of required extension (which is perfectly fine).

As with the 16-bit input/output sample, I think these should probably be extension samples rather than performance samples, especially as this one is not universally supported. I'm otherwise happy to call this approved after the above has been discussed in the call.

**Review by r-potter — DISMISSED** [review]

**Review by carlosadcq — DISMISSED** [review]

**Comment by marty-johnson59** [comment]
@HansKristian-Work, do you know how to resolve the branch conflict above so this can be merged?

**Comment by HansKristian-Work** [comment]
@marty-johnson59 The problem with rebasing is that all approvals are automatically cancelled, and I don't know how long the sample merge will be delayed just because of that.

The resolve is trivial, it's just two lines in the README.md where two samples were both added at the end.

Does using Resolve conflicts in the Github UI avoid this problem?

**Comment by marty-johnson59** [comment]
It's not letting me resolve on github...or merge.  But if we do re-base to fix the conflict, I can probably go ahead and merge w/o waiting for the approvals...it it lets me over-ride that requirement..

**Comment by gpx1000** [comment]
Sorry about that tried to help by fixing the merge conflict.  It should be able to be merged now.

**Comment by HansKristian-Work** [comment]
CI is failing on commits that used to pass now.

**Comment by marty-johnson59** [comment]
Merging as we had 3 approvals prior to trivial branch conflict

**Comment by marty-johnson59** [comment]
@HansKristian-Work Oops, may have jumped the gun..  Can you update the copyright header to 2021?  Any idea what the clang format check is complaining about?

**Comment by HansKristian-Work** [comment]
@marty-johnson59 you want a new PR with copyrights updated?

**Comment by marty-johnson59** [comment]
Sorry, yes, we need to keep the legal stuff clean...

**Comment by HansKristian-Work** [comment]
@marty-johnson59 https://github.com/KhronosGroup/Vulkan-Samples/pull/244

**Pull request merged**
