### PR TITLE
CMake 3.12 -> CMake 3.10.2

### LINKED ISSUE #346: Updated CMake requirement may be problematic on Android
With the merge of the plugins branch, the CMake requirement was raised from CMake 3.10 to 3.12.

Android Studio only offers CMake 3.6, 3.10 and 3.18. Sadly the CMake version 3.18 offered by google is broken, so right now there is no way to compile the samples with an up-to-date Android studio.

I'm not sure how we should handle this. The easiest way would be dropping the CMake requirement back to 3.10, though I'm not sure if that's possible.

### PR DESCRIPTION
**Pull request by TomAtkinsonArm**
## Description

The project cannot use a higher CMake version due to Android Studios CMake version 3.18 being broken. To make sure that the project can be built and run on all supported platforms I have removed the 3.12 specific syntax and replaced with the previous implementation.

Replace JOIN

`list(JOIN <list> <glue> <out-var>)` -> `string_join(INPUT <list> GLUE <glue> OUTPUT <out-var>)`

Replace `file(GLOB CONFIGURE_DEPENDS)`

`GLOB` used with `CONFIGURE_DEPENDS` would re-run the `GLOB` operation if CMake detected changes in the file structure. This has been replaced with a regex replace of a hardcoded list. See `plugins/CMakeLists.txt:52-64`.

In the future I hope we can bump our CMake version higher to simplify our CMake with its newer features

Fixes #346

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by SaschaWillems** [comment]
Can't get this to build either. I'm slowly thinking that google is trying everything possible to make people drop support for native NDK development. I tried for hours to get this working, but to no avail.

The CMake version error is gone, but now I'm getting an error about a relative path for every sample included in the project:

```Execution failed for task ':generateJsonModelDebug'.
> V:\Vulkan-KHR-Samples\Vulkan-Samples-KHR\CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error in samples/api/dynamic_uniform_buffers/CMakeLists.txt:
    Found relative path while evaluating include directories of
    "dynamic_uniform_buffers":

```

And yes, the empty line is supposed to contain that relative path. But it's either empty or contains a random unicode char.

Does this work for you in Android Studio? If so, I expect my installation is broken once again and I'll try to do a clean install.

**Comment by gpx1000** [comment]
I have it building with the original 3.12+ in Android Studio.  It took correcting the older build.gradle that's generated.  Gimme a bit and I'll come up with a PR that gets this fixed without the need for this PR.

**Comment by TomAtkinsonArm** [comment]
@gpx1000 either way, the CMake 3.12 features used are negligible. If this PR allows the majority of users to use the OOB CMake version with Android Studio then removing these features may stull be useful?

**Review by gpx1000 — APPROVED** [review]

**Comment by TomAtkinsonArm** [comment]
Fixed by #348

**Pull request closed without merging**
