### PR TITLE
CLI11 / CLI changes

### PR DESCRIPTION
**Pull request by TomAtkinsonArm**
## Description

- Changes to the CLI wrapper class
- CLI implementation with CLI11
- Required for plugins to extend the API

To overcome short falls of docopt's regex capabilities it was necessary to switch to a different CLI library and to allow for other forms of configuration (*cough* JSON *cough*) in the future by using small interface named CommandParser.

CommandParser treats commands a tree, each node of the tree is visited at the point commands are parsed. Each type of command will have its own `parse(context, command_type)` method to implement its own custom behaviour.

`get_int` `get_string` `get_XX` methods are now replaced with `as<Type>(command*)`. This allows for the implementation of more types without the redefinition of logic. If a type is requested that is not supported then the program will assert until that type is implemented.

`--help`

image

`batch --help`

image

## Notes

This PR is not to improve the apps current functionality and so comments pointing out application logic and not the contents of the PR may be deferred to later PRs. This is because many aspects that this PR work on are pre-plugins and so are already reworked or removed

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist
(Doesn't apply to this change)

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Review by gary-sweet — APPROVED** [review]

**Comment by SaschaWillems** [comment]
This doesn't seem to work for me with VS2019 on Windows 10. No matter how I try to pass the arguments, I always get the following output:

```[info] Logger initialized
[info] Window created
[error] [build\windows\app\main.cpp:73] Failed to find a create function for
Press enter to close...
```
I tried with
```
vulkan_samples.exe hdr
vulkan_samples.exe --sample hdr
```
(using various sample names, the error is always the same)

What I did:
- Switch to this PR from master
- git submodule init
- git submodule update (to fetch the cli11 submodule)
- Delete the CMake cache
- CMake configure
- Clean rebuild in VS2019

**Comment by TomAtkinsonArm** [comment]
> VS2019 on Windows 10

I was able to build and run with this same setup. Did you use any specific flags when generating the build?

**Comment by gpx1000** [comment]
FWIW, this works here in Linux and OSX.  I haven't tested Windows yet.

**Comment by marty-johnson59** [comment]
Hi Tom, can  you fix the CI issue here (Clang format check)?  Then I'll ask for reviews.  Thanks!

**Comment by SaschaWillems** [comment]
I did some more investigation, and it only fails when building in release mode, while a debug build works fine. Trying to debug a ReleaseWithDebInfo I can see that the sample name I passed is there, exactly as it's the case with the debug build:

image

But the sample name passed to the app prepare function is empty:
image

Running this in a debug build, the values (in the debugger) are the same, but the sample name is properly passed.

So maybe this is some problem with a variable getting optimized away in a release build? Can you test in a debug build and see if this also fails for you?

**Comment by TomAtkinsonArm** [comment]
@marty-johnson59  :)

> Hi Tom, can you fix the CI issue here (Clang format check)? Then I'll ask for reviews. Thanks!

https://github.com/KhronosGroup/Vulkan-Samples/pull/285

**Comment by TomAtkinsonArm** [comment]
I've run this change today in debug, release builds compiled with vs 2017 and vs 2019 separately.

I used `--sample instancing`, `instancing` for instancing, subpasses and afbc.

Each time it loads the application correctly. I also tried with `raytracing_basic` which loaded correctly but my GPU doesn't support that extension so inevitably crashes.

My project is set up as normal, clone, cleaned cache, updated submodules. Do you have anything different in your set up @SaschaWillems?

**Comment by SaschaWillems** [comment]
Did a clean checkout, deleted all caches and update the submodules and it's now working as expected :)

**Review by SaschaWillems — APPROVED** [review]

**Review by gpx1000 — APPROVED** [review]

**Comment by marty-johnson59** [comment]
Are we OK to merge this with the Clang Format Check failure?

**Pull request merged**
