### PR TITLE
Resolve validation layer issues in API samples.

### PR DESCRIPTION
**Pull request by asuessenbach**
## Description

Resolved validation layer issues in API samples:
- [hpp_]compute_nbody: `VK_PIPELINE_STAGE_VERTEX_INPUT_BIT` (`vk::PipelineStageFlagBits::eVertexInput`) is not specified for usage in a compute pipeline. Replaced it by `VK_PIPELINE_STAGE_TRANSFER_BIT` (`vk::PipelineStageFlagBits::eTransfer`) in the barriers.
- [hpp_]instancing, [hpp_]texture_mipmap_generation: removed attribute descriptions of unused locations

Built on Win11/VS2022, tested on NVIDIA HW.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by SaschaWillems** [comment]
LGTM. Ran the samples mentioned in this PR with the latest SDK and didn't get any validation layer messages.

**Review by SaschaWillems — APPROVED** [review]

**Review by gary-sweet — COMMENTED** [review]
Is this meant to resolve validation in all API samples, or just the ones listed?

I still see validation errors in hdr and hpp_hdr.

**Comment by gary-sweet** [comment]
> Is this meant to resolve validation in all API samples, or just the ones listed?
> 
> I still see validation errors in hdr and hpp_hdr.

`
VUID-VkGraphicsPipelineCreateInfo-renderPass-06041(ERROR / SPEC): msgNum: 1831492259 - Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06041 ] Object 0: handle = 0x2721df80, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6d2a5aa3 | vkCreateGraphicsPipelines(): pipeline.pColorBlendState.pAttachments[0].blendEnable is VK_TRUE but format VK_FORMAT_R32G32B32A32_SFLOAT of the corresponding attachment description (subpass 0, attachment 0) does not support VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT. The Vulkan spec states: If renderPass is not VK_NULL_HANDLE, and the pipeline is being created with fragment output interface state, then for each color attachment in the subpass, if the potential format features of the format of the corresponding attachment description do not contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT, then the blendEnable member of the corresponding element of the pAttachments member of pColorBlendState must be VK_FALSE (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06041)
    Objects: 1
        [0] 0x2721df80, type: 3, name: NULL
`

`VUID-vkCmdDraw-blendEnable-04727(ERROR / SPEC): msgNum: -1466709161 - Validation Error: [ VUID-vkCmdDraw-blendEnable-04727 ] Object 0: handle = 0x6b000000006b, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0xa893cb57 | vkCmdDraw: Image view's format features of the color attachment (0) of the active subpass do not contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT bit, but active pipeline's pAttachments[0].blendEnable is not VK_FALSE. The Vulkan spec states: If rasterization is not disabled in the bound graphics pipeline, then for each color attachment in the subpass, if the corresponding image view's format features do not contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT, then the blendEnable member of the corresponding element of the pAttachments member of pColorBlendState must be VK_FALSE (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdDraw-blendEnable-04727)`

**Comment by asuessenbach** [comment]
@gary-sweet Well, yes, it was supposed to resolve all validation layer issues in all API samples.
And in fact, I don't get those messages. Are you using a newer validation layer version?

**Comment by gary-sweet** [comment]
> @gary-sweet Well, yes, it was supposed to resolve all validation layer issues in all API samples. And in fact, I don't get those messages. Are you using a newer validation layer version?

I'm currently using v1.3.226 of the validation layers.

**Comment by asuessenbach** [comment]
Strange thing. I'm using 1.3.231.
Do you get the errors right after starting, or do you need to interact somehow?

**Comment by gary-sweet** [comment]
> Strange thing. I'm using 1.3.231. Do you get the errors right after starting, or do you need to interact somehow?

The errors appear right away, no interaction required.

I looks like it's related to the sample enabling blending on a R32G32B32A32_SFLOAT attachment. VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT is not mandatory on that format, and I suspect the sample isn't checking.

It's likely that your hardware does support it, which would mean you don't see the validation error. Ours only supports blending on 8-bit & 16-bit types. If I change the format to 16f the validation errors go away (though support for blending should still really be checked).

**Comment by asuessenbach** [comment]
> It's likely that your hardware does support it

I see... That is, @SaschaWillems as the official owner of this sample or you, @gary-sweet, as the one with the picky HW, should adjust those two samples accordingly?

**Review by TomAtkinsonArm — APPROVED** [review]

**Comment by SaschaWillems** [comment]
Sure, I'll take a look at this and add proper runtime format selection.

**Pull request merged**
