### PR TITLE
hello_triangle sample should avoid referencing a retired swapchain #1015

### LINKED ISSUE #1015: hello_triangle sample references a retired swapchain
`hello_triangle.cpp` references a retired swapchain resulting in a warning on Android:

> 04-08 21:49:23.966 19681 20951 W vulkan  : getting images for non-active swapchain 0xb400007623312000; only dequeued image handles are valid

```
void HelloTriangle::init_swapchain(Context &context)
{
	VkSurfaceCapabilitiesKHR surface_properties;
	VK_CHECK(vkGetPhysicalDeviceSurfaceCapabilitiesKHR(context.gpu, context.surface, &surface_properties));
...
VkSwapchainCreateInfoKHR info{VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR};
info.surface            = context.surface;
info.minImageCount      = desired_swapchain_images;
info.imageFormat        = format.format;
info.imageColorSpace    = format.colorSpace;
info.imageExtent.width  = swapchain_size.width;
info.imageExtent.height = swapchain_size.height;
info.imageArrayLayers   = 1;
info.imageUsage         = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;
info.imageSharingMode   = VK_SHARING_MODE_EXCLUSIVE;
info.preTransform       = pre_transform;
info.compositeAlpha     = composite;
info.presentMode        = swapchain_present_mode;
info.clipped            = true;
info.oldSwapchain       = old_swapchain;

VK_CHECK(vkCreateSwapchainKHR(context.device, &info, nullptr, &context.swapchain));

if (old_swapchain != VK_NULL_HANDLE)
{
	for (VkImageView image_view : context.swapchain_image_views)
	{
		vkDestroyImageView(context.device, image_view, nullptr);
	}

	uint32_t image_count;
	VK_CHECK(vkGetSwapchainImagesKHR(context.device, old_swapchain, &image_count, nullptr));
	for (size_t i = 0; i < image_count; i++)
	{
		teardown_per_frame(context, context.per_frame[i]);
	}

	context.swapchain_image_views.clear();

	vkDestroySwapchainKHR(context.device, old_swapchain, nullptr);
}
...
```
Vulkan spec states that 

> Upon calling vkCreateSwapchainKHR with an oldSwapchain that is not [VK_NULL_HANDLE](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_NULL_HANDLE.html), oldSwapchain is retired — even if creation of the new swapchain fails. The new swapchain is created in the non-retired state whether or not oldSwapchain is [VK_NULL_HANDLE](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_NULL_HANDLE.html).

`VK_CHECK(vkCreateSwapchainKHR(context.device, &info, nullptr, &context.swapchain));` retires `old_swapchain` and `VK_CHECK(vkGetSwapchainImagesKHR(context.device, old_swapchain, &image_count, nullptr));` references it.

```
uint32_t image_count;
VK_CHECK(vkGetSwapchainImagesKHR(context.device, old_swapchain, &image_count, nullptr));
```
should precede 
`VK_CHECK(vkCreateSwapchainKHR(context.device, &info, nullptr, &context.swapchain));`

### PR DESCRIPTION
**Pull request by yaman-lunarg**
## Description

By obtaining the image_count prior to the retirement of old_swapchain, Android warning is prevented.

Fixes #1015 

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the readme of the folder that the sample belongs to [e.g. api samples readme](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/api/README.adoc)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/conditional_rendering)
- [ ] For new samples, I have added a link to the [Antora navigation](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

### CODE REVIEW

**Comment by asuessenbach** [comment]
As I don't have an Android environment to test, I can't tell if this change is valid. But it looks a bit strange...
If it actually is an issue, could you please adjust hpp_hello_triangle accordingly?

**Comment by marty-johnson59** [comment]
HI @yaman-lunarg, this is still labeled "draft".  Any thoughts on next steps?  Thanks

**Comment by bradgrantham-lunarg** [comment]
Yaman no longer is available at that login.  We probably won't carry forward this PR, we don't have any resource to handle the long to-do list.

We noted this failure on Android in logcat:

> Running some vulkan samples, for example Hello Triangle on android with gfxr enabled a warning is issued:
> 
> `02-27 19:12:17.625 31072 31130 W vulkan : getting images for non-active swapchain 0xb400007a8dd3ef70; only dequeued image handles are valid`
> 
> It comes from here: https://android.googlesource.com/platform/frameworks/native/+/android-8.1.0_r9/vulkan/libvulkan/swapchain.cpp#1173
> 
> I've gotten this on Pixel 6, to reproduce just run Vulkan Samples and choose the Hello Triangle sample, with gfxr enabled

In reply to @asuessenbach the current code is incorrect under the spec (but there may not be a VUID).  Passing `old_swapchain` to `CreateSwapchainKHR` makes `old_swapchain` retired, and images cannot then be acquired from that swapchain.  This PR makes sure the images are acquired *before* the swapchain is retired.

> **Retired Swapchain**
> A swapchain that has been used as the oldSwapchain parameter to [vkCreateSwapchainKHR](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vkCreateSwapchainKHR). Images cannot be acquired from a retired swapchain, however images that were acquired (but not presented) before the swapchain was retired can be presented.

**Comment by SaschaWillems** [comment]
As I'm working on updating the hello triangle sample I can take a look at that and would do a new PR to fix this.

**Comment by SaschaWillems** [comment]
As per discussion, I'll provide a new PR that does things differently. So closing this.

**Pull request closed without merging**
