### PR TITLE
WIP: Shared target libs for faster builds

### LINKED ISSUE #366: Linux makefile build serializes during middle of build
The linux build serializes down to a single core during the middle of the build (I'd estimate 90% of the build time is spent in this serialized section). The start and end of the build use all cores as expected. I can't see any dependencies that would be causing this, but I'm no cmake expert.

### PR DESCRIPTION
**Pull request by gpx1000**
## Description

This is an ongoing effort to switch from static to shared libraries with the goal to decrease the memory requirements on linking and also decrease the build time requirements.

Fixes #366

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by gary-sweet** [comment]
This change helps my build performance massively.
A full build after clean previously took 9.5 minutes, and takes only 35 seconds with this change in place.

**Comment by SaschaWillems** [comment]
I'd love to do QA on this, but on Windows the build fails due to unresolved externals in the astc third party library. Any way around this? Github CI also fails with that error.

**Review by tomadamatkinson — APPROVED** [review]

**Review by SaschaWillems — APPROVED** [review]
This does significantly lower build times for me too. Changes to the framework still take more than 3 minutes to build for me, hopefully we'll be able to cut this down further.

LGTM

**Review by gary-sweet — APPROVED** [review]
Much faster for me

**Pull request merged**
