### PR TITLE
open_gl_interop: Update glad generated files

### PR DESCRIPTION
**Pull request by caramelli**
glad.h and glad.c were generated with --api="gl=4.3,gles2=3.2" which leads to the following definitions in glad.h:

#ifndef GL_ES_VERSION_3_1
\# define GL_ES_VERSION_3_1 1
  GLAPI int GLAD_GL_ES_VERSION_3_1;
  typedef void(APIENTRYP PFNGLMEMORYBARRIERBYREGIONPROC)(GLbitfield barriers);
  GLAPI PFNGLMEMORYBARRIERBYREGIONPROC glad_glMemoryBarrierByRegion;
\# define glMemoryBarrierByRegion glad_glMemoryBarrierByRegion
#endif
#ifndef GL_ES_VERSION_3_2
\# define GL_ES_VERSION_3_2 1
  GLAPI int GLAD_GL_ES_VERSION_3_2;
  typedef void(APIENTRYP PFNGLBLENDBARRIERPROC)(void);
  GLAPI PFNGLBLENDBARRIERPROC glad_glBlendBarrier;
\# define glBlendBarrier glad_glBlendBarrier
  ...

This conflicts with the declaration of the corresponding OpenGL 4.5 prototypes.
So --api="gl=4.5,gles2=3.2" is used instead of --api="gl=4.3,gles2=3.2" for the generation.

Nicolas Caramelli

### CODE REVIEW

**Comment by caramelli** [comment]
This raises me questions when using clang-format on generated files (glad.h and glad.c in this case), or coming from a "third party" (here khrplatform.h from the Khronos Group) ...
But it is now consistent with the previous files.

**Comment by wasimabbas-arm** [comment]
> This conflicts with the declaration of the corresponding OpenGL 4.5 prototypes.

I don't think I understand what the issue is here. Where did these corresponding 4.5 prototypes comes from that you are having a conflict with? You are basically upgrading the headers to 4.5 why is this required? Perhaps provide an example that should help clarify the issue you are proposing to solve.

**Comment by caramelli** [comment]
Yes, this change just updates the glad generated files for 4.5

As explained, glad.h contains:

\# define glMemoryBarrierByRegion glad_glMemoryBarrierByRegion

When building for Linux, <GL/gl.h> is included by glfw3.h in offscreen_context.h and the <GL/gl.h> on my system contains OpenGL 4.5:

#ifndef GL_VERSION_4_5
...
GLAPI void APIENTRY glMemoryBarrierByRegion (GLbitfield barriers);

Because the glad generation is limited to 4.3, the preprocessor replaces

    GLAPI void APIENTRY glMemoryBarrierByRegion (GLbitfield barriers);

by

    extern void glad_glMemoryBarrierByRegion (GLbitfield barriers);

and the build fails with:

gl.h: error: 'void glad_glMemoryBarrierByRegion(GLbitfield)' redeclared as different kind of symbol
  GLAPI void APIENTRY glMemoryBarrierByRegion (GLbitfield barriers);

glad.h: note: previous declaration 'void (* glad_glMemoryBarrierByRegion)(GLbitfield)'
  GLAPI PFNGLMEMORYBARRIERBYREGIONPROC glad_glMemoryBarrierByRegion;

With this change, the updated glad.h contains:

#ifndef GL_VERSION_4_5
\#	define GL_VERSION_4_5 1
...

So there are no more conflict.

You can easily reproduce the issue by adding the following code in offscreen_context.h right after # include <GLFW/glfw3.h>

#ifndef GL_VERSION_4_5
GLAPI void APIENTRY glMemoryBarrierByRegion (GLbitfield barriers);
#endif

Hope this helps to clarify.

**Comment by ghost** [comment]
@jherico - Would appreciate your input on this PR.

**Comment by ghost** [comment]
@caramelli - we have changed CI provider but in order for the checks to run again with the new CI could you either: 

a) submit an empty commit using git commit -m "" --allow-empty

or

b) squash some commits and push

thanks!

**Comment by caramelli** [comment]
Yes, of course. It should be OK.

**Review by gary-sweet — COMMENTED** [review]
Builds and runs without issue for Broadcom, but we don't support the GL interop, so someone else will need to approve.

**Comment by r-potter** [comment]
Builds fine for Android, but we can't test it, so needs desktop vendors to approve

**Comment by SaschaWillems** [comment]
Builds and runs fine on Windows 10 on a NVIDIA RTX 2060 with the latest drivers. It crashes in the destructor due to a double deletion, but that has been fixed with #206. 

So this works as expected on Desktop.

**Comment by marty-johnson59** [comment]
Per discussion on the 11/23 call, this one is pending reviews/approvals by the DT vendors. @mattruschnv, @aurolou, can you please review? Thanks!

**Review by aurolou — APPROVED** [review]

**Comment by marty-johnson59** [comment]
As this is DT specific, we agreed to merge this at the Dec 7th meeting - approved by AMD and doesn't break on mobile platforms

**Pull request merged**
