### PR TITLE
Refactored API sample hpp_timestamp_queries; includes minor adjustments in API samples hpp_hdr and hpp_terrain_tessellation.

### PR DESCRIPTION
**Pull request by asuessenbach**
## Description

Besides the refactoring of the sample `hpp_timestamp_queries`, this PR includes
- new helper function `vkb::common::create_query_pool` in `framework/common/hpp_vk_common.hpp` and
- minor adjustments in the samples `hpp_hdr` and `hpp_terrain_tessellation`.

Build tested on Win10 with VS2022. Run tested on Win10 with NVidia GPU.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
  
## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](./../samples/extensions/conditional_rendering)
- [ ] For new samples, I have added a link to the [Antora navigation](./../antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

### CODE REVIEW

**Review by gary-sweet — COMMENTED** [review]
I'm struggling to see how the hpp_hdr changes have anything to do with the bulk of this change.
It looks like they should be in a separate PR to me. Have I missed something?

**Comment by asuessenbach** [comment]
@gary-sweet You're right, the changes in `hpp_hdr` could easily be moved into a separate PR.
It's just that `hpp_hdr` and `hpp_timestamp_queries` are very similar, and with the changes in `hpp_hdr`, they are both using the same naming schemes on functions (`prepare_stuff`, instead of `setup_stuff`).
If you think, it's better to separate that into two PR, I'll be happy to do so.

**Comment by SaschaWillems** [comment]
Imo it's fine to do it in one PR, but maybe change the title so it reflects the change to multiple samples?

**Comment by SaschaWillems** [comment]
No clue why, but with this PR I get wrong statistics values displayed in the terrain tessellation sample:
vulkan_samples_UY1FJsmhBj

Correct values are sometimes visible for a short amount of time, but at higher frame rates I always get the wrong values displayed. So this maybe a timing problem.

The non-HPP variant works fine. Tested on an RTX 4070 with Win11 and the latest Game Ready driver. I had this exact same problem back with my RTX 2060 and Win10 but was never able to pinpoint it.

The code changes themselves look fine though.

**Comment by asuessenbach** [comment]
> No clue why, but with this PR I get wrong statistics values displayed in the terrain tessellation sample:

No clue, either! Especially as I can't reproduce that strange behaviour.
Can anybody else repro it?
@SaschaWillems
- Do you run that in release or debug mode?
- Could you break in `HPPTerrainTessellation::on_update_ui_overlay` if `statistics.results[0]` is greater than, maybe, 100000?
- Could you add a waitIdle to HPPTerrainTessellation::draw(), like this:
```
	if (statistics.query_supported)
	{
		// Read query results for displaying in next frame
		get_device()->get_handle().waitIdle();
		statistics.results =
		    get_device()->get_handle().getQueryPoolResult<std::array<uint64_t, 2>>(statistics.query_pool, 0, 1, sizeof(statistics.results), vk::QueryResultFlagBits::e64).value;
	}
```

**Comment by SaschaWillems** [comment]
> Do you run that in release or debug mode?

Debug

> Could you break in HPPTerrainTessellation::on_update_ui_overlay if statistics.results[0] is greater than, maybe, 100000?

Just did and the break point is hit every other frame with very large values:

image

Putting the same conditional breakpoint in the non-HPP variant of the sample doesn't trigger

> Could you add a waitIdle to HPPTerrainTessellation::draw(), like this:

That fixes the problem. So it looks like a sync/timing problem that somehow only happens with the HPP sample.

P.S. : Feel free to move this to a different PR if that works better for you.

**Comment by asuessenbach** [comment]
@SaschaWillems If I got it right, that error is independent from this PR, right? You also get it with the current main branch, for example?
As I don't see anything like this, and the VulkanConfigurator doesn't tell me any issue here, it's hard to fix... I assume, you don't have any local changes in your repository that might affect this sample?
As asked before: does anybody else see this error?

**Comment by SaschaWillems** [comment]
Exactly. It also happens on master, so it's not related to this PR. I have reponed the issue #674  where I first reported this and will continue discussion in there.

**Review by gary-sweet — APPROVED** [review]

**Review by SaschaWillems — APPROVED** [review]

**Pull request merged**
