### PR TITLE
Fix several SYNC-HAZARD WAW errors in the framework.

### PR DESCRIPTION
**Pull request by congyue1977**
## Description

1.GUI font image barrier in the framework.
2.Subpass dependencies in the framework.
3.Subpass dependencies in the fragment_shading_rate sample.

Fixes #<issue number>

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by congyue1977** [comment]
image
I don't know why the windows build failed?

**Comment by congyue1977** [comment]
@SaschaWillems 
Could you please help me check this problem?

**Comment by SaschaWillems** [comment]
Looks like an internal (github) problem. I have rerun the jobs, hopefully they'll all work now.

**Comment by congyue1977** [comment]
> Looks like an internal (github) problem. I have rerun the jobs, hopefully they'll all work now.

Thank you, it works.

**Review by SaschaWillems — APPROVED** [review]
Changes look good to me. Synchronization validation no longer reports sync errors for me.

**Review by gpx1000 — APPROVED** [review]

**Review by TomAtkinsonArm — APPROVED** [review]

**Comment by marty-johnson59** [comment]
merging with 3 approvals.  LMK if issues

**Pull request merged**
