### PR TITLE
Refactor API sample hpp_hdr

### PR DESCRIPTION
**Pull request by asuessenbach**
## Description

Includes adjustments in API samples hpp_compute_nbody and hpp_dynamic_uniform_buffers.

Builds and runs on Win10 on NVidia HW.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x]I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by asuessenbach** [comment]
The clang format check is failing on this PR, and it seems to fail on hpp_hdr.h.
But I did format that file and I can't recognize what the problem might be here.
Any ideas on how to resolve that failure?

**Comment by SaschaWillems** [comment]
What Visual Studio Version are you using? For VS2019 (and lower) you may have to manually update the clang tools to get it to format properly.

**Comment by asuessenbach** [comment]
I'm using clang-format 15.05 (out of VS2022).

**Comment by SaschaWillems** [comment]
Just did a "format document" in `hpp_hdr.h` with VS2022 Version 17.5.1 and it did change indentation for me. I have attached the patch file, maybe you can apply it and see if the Clang Format Check fail will be resolved.

[diff.patch](https://github.com/KhronosGroup/Vulkan-Samples/files/11068685/diff.patch)

**Comment by asuessenbach** [comment]
@SaschaWillems Thanks a lot for that patch. Obviously, it helped!

**Comment by asuessenbach** [comment]
@SaschaWillems Thanks a lot for that patch. Obviously, it helped!

**Review by SaschaWillems — APPROVED** [review]

**Review by gpx1000 — APPROVED** [review]

**Review by gary-sweet — APPROVED** [review]

**Comment by marty-johnson59** [comment]
Merging w/ 3 approvals

**Pull request merged**
