### PR TITLE
Fix incorrect src access mask in GLTF image upload

### LINKED ISSUE #38: Incorrect barrier in GLTF upload
[source access mask](https://github.com/KhronosGroup/Vulkan-Samples/blob/af0dbc2ec3a872688265e355d997070fd50813ac/framework/gltf_loader.cpp#L320) should be `VK_ACCESS_TRANSFER_WRITE_BIT`

### PR DESCRIPTION
**Pull request by jherico**
## Description

Fix #38

## General Checklist:

Please ensure the following points are checked:

- [X] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [X] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [X] I have commented any added functions (in line with Doxygen)
- [X] I have commented any code that could be hard to understand
- [X] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [X] I have used existing framework/helper functions where possible
- [X] My changes build and run on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)

### CODE REVIEW

**Comment by ZandroFargnoli** [comment]
Adding this flag causes validation errors on an S8 Adreno.

```
2019-05-27 12:06:40.851 12234-13129/com.khronos.vulkan_samples E/VulkanSamples: [error] [s available, enabling it:33] Validation:  [ VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184 ] Object: 0x7bb51fe010 (Type = 6) | vkCmdPipelineBarrier(): pImageMemBarriers[0].srcAccessMask (0x1000) is not supported by srcStageMask (0x4000). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its srcAccessMask member if that bit is not supported by any of the pipeline stages in srcStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184)
2019-05-27 12:06:40.882 12234-13129/com.khronos.vulkan_samples E/VulkanSamples: [error] [s available, enabling it:33] Validation:  [ VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184 ] Object: 0x7bb51fe010 (Type = 6) | vkCmdPipelineBarrier(): pImageMemBarriers[0].srcAccessMask (0x1000) is not supported by srcStageMask (0x4000). The spec valid usage text states 'Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its srcAccessMask member if that bit is not supported by any of the pipeline stages in srcStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01184)
```

**Comment by jherico** [comment]
That's confusing, because there's no place in the code where I see a combination of `VK_ACCESS_TRANSFER_WRITE_BIT` and `VK_PIPELINE_STAGE_HOST_BIT` in the same barrier.  Also I get no validation error on my desktop, which suggests to me that the adreno validation failure is a false positive from an older version of the validation layers.

**Comment by jherico** [comment]
I can't find any previous bug in the validation layers that would explain this behavior, but I also can't explain the combination of srcAccessMask 0x1000 `VK_ACCESS_TRANSFER_WRITE_BIT` and srcStageMask 0x4000 `VK_PIPELINE_STAGE_HOST_BIT`.  I'm attempting to do an android build now but I only have the following devices to test:  Pixel, Pixel 3a, S9 and S6 

Can you provide more detail as to what example was being run when you encountered this warning?  I know the performance examples that load the Sponza scene exercise this code path, but I'm not sure if anything else does.

**Comment by jherico** [comment]
I've tested on my Pixel 3a, and run the render_passes performance example, which I know exercises the changed code.  The logcat of initialization and starting to render is located [here](https://gist.github.com/jherico/625917ee1411fa9ad7832041e9d1b1b2).  You can see from the logging that validation _is_ enabled (I had to manually modify the cmake arguments in the gradle file to trigger this).

I can't reproduce the validation message. 

I'll try testing on the S6 as well (once it gains sufficient charge), but the behavior suggests a bug in either the validation layers or the driver on the S8 Adreno.  The validation layers are not device specific, so given the same client code I should generate the same errors you're getting.

**Comment by ZandroFargnoli** [comment]
That's weird, I can't seem to reproduce these validation messages anymore, everything looks clean to me now.

**Review by ZandroFargnoli — APPROVED** [review]
LGTM

**Review by JoseEmilio-ARM — APPROVED** [review]

**Review by wasimabbas-arm — APPROVED** [review]

**Pull request merged**
