### PR TITLE
Added support for spot lights

### PR DESCRIPTION
**Pull request by ZandroFargnoli**
## Description

* Added support in the shaders for spot lights, and added a utility function to add a spot light to the scene graph.
* Removed dynamic branching, shaders should now see a speed up in performance
* Added pre-compilation of shaders. You can now use #includes to include common code inside your shaders.

image (2)

Code example:

```
auto &spot_light = vkb::add_spot_light(*scene, camera_node.get_transform().get_translation(), camera_node.get_transform().get_rotation());
spot_light.set_properties({
	{0.0f, 0.0f, -1.0f},                     // Direction
	{1.0f, 0.95f, 0.7f},                    // Color (yellowish white)
	1.0f,                                        // intensity
	5.0f,                                        // range
	glm::cos(glm::radians(12.5f)), // inner cone angle (required for spot lights)
	glm::cos(glm::radians(15.5f))  // outer cone angle (required for spot lights)
});
```

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build and run on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)

### CODE REVIEW

**Review by r-potter — APPROVED** [review]

**Review by AlejandroCosin — DISMISSED** [review]

**Comment by gary-sweet** [comment]
This has a very noticeable performance degradation on things like the render_passes sample for me (~30% lower fps).
Dynamic switching like this in shaders costly on some architectures, especially when the code won't actually be used most of the time. Some architectures will be using predication rather than branching for example.

Could we not control whether the specific lighting blocks are needed with a specialization constant for example? Wouldn't that be a better 'best practice' in general?

I'm also seeing a compilation error when running render_subpasses:

```
[error] [framework/core/shader_module.cpp:50] Shader compilation failed for shader "deferred/lighting.frag"
[error] [framework/core/shader_module.cpp:51] ERROR: :69: 'light' : no such field in structure 
ERROR: :69: '-' :  wrong operand types: no operation '-' exists that takes a left-hand operand of type ' in highp 3-component vector of float' and a right operand of type 'layout( set=0 binding=4 column_major std140) uniform block{layout( column_major std140) uniform highp uint count, layout( column_major std140) uniform 100-element array of structure{ global highp 4-component vector of float position,  global highp 4-component vector of float color,  global highp 4-component vector of float direction,  global highp 2-component vector of float info} lights}' (or there is no acceptable conversion)
ERROR: :69: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
```

**Review by gary-sweet — CHANGES_REQUESTED** [review]
See my top-level comment

**Review by r-potter — CHANGES_REQUESTED** [review]
Retested on Mali and Adreno. I don't see significant performance cost to the shaders on these GPUs, but I agree with Gary's expectations re: predicating compilers/architectures.

I do see the same compilation errors as Gary in the subpasses sample.

**Comment by gary-sweet** [comment]
So, the problem in command_buffer_usage is now fixed, thanks.

However, pipeline_barriers, layout_transitions and specialization_constants all fail to run with the following error:
```
terminate called after throwing an instance of 'fmt::v5::format_error'
  what():  invalid format string
Aborted
```

**Comment by gary-sweet** [comment]
Now I get this on specialization_constants:
```
[error] [framework/core/shader_module.cpp:106] Shader compilation failed for shader "specialization_constants/specialization_constants.frag"
[error] [framework/core/shader_module.cpp:107] ERROR: :50: 'MAX_FORWARD_LIGHT_COUNT' : undeclared identifier 
```

**Comment by gary-sweet** [comment]
Specialization constants is now fixed, thanks.

However, I'm seeing some serious issues with command_buffer_usage:
I turn on multi-threading and then choose 4 or more secondary command buffers. I start to see some of the objects flickering in and out of existence (or just rendering badly - I'm not sure).  When I keep increasing the secondary buffer count I eventually see a GPU lockup. None of this happens on the master branch.

**Comment by ZandroFargnoli** [comment]
>However, I'm seeing some serious issues with command_buffer_usage:
I turn on multi-threading and then choose 4 or more secondary command buffers. I start to see some of the objects flickering in and out of existence (or just rendering badly - I'm not sure). When I keep increasing the secondary buffer count I eventually see a GPU lockup. None of this happens on the master branch.

I am not seeing these issues myself on Windows, however I believe I have fixed the issue. The lights were being allocated per secondary command buffer - so I've moved the allocation to be done per draw and then they are bound (like we've done before). But the specialization constants that you requested are now fed in per bind.

**Review by gary-sweet — DISMISSED** [review]

**Review by gary-sweet — COMMENTED** [review]
Taking my approval back off for the moment while I look at the code some more.

**Review by gary-sweet — DISMISSED** [review]
LGTM now.

**Review by gary-sweet — APPROVED** [review]

**Review by aurolou — APPROVED** [review]

**Review by AlejandroCosin — APPROVED** [review]

**Pull request merged**
