### PR TITLE
Fix sccache usage in Windows CI builds

### PR DESCRIPTION
**Pull request by jherico**
## Description

This corrects a couple problems preventing the Windows CI builds from using sccache.  

Fix for #896 and reduces windows build significantly.

### CODE REVIEW

**Comment by jherico** [comment]
@gpx1000 You mentioned having trouble getting sccache working in Windows CI builds.  I was able to track it down after I noticed something odd in the beginning of the CMake config.  

The basic issue was twofold...  

* Although sccache doesn't work with the Visual Studio generator, some sources online seem to suggest it works with the "NMake Makefiles" generator, but as far as I can tell it does not.  Switching to Ninja works though.
* The online commentary about the need to use `/Z7` instead of `/Zi` may be accurate, but the mechanism that was being used didn't work for the reasons I noted in #896

**Review by tomadamatkinson — DISMISSED** [review]
Nice! Looks like this cuts the Windows build down from ~30minutes to ~7minutes in the CI

**Comment by jherico** [comment]
It occurred to me that I should revert the change adding messaging about lack of ccache or sccache since they don't work with the most commonly used Windows generators.  I could gate them behind a `if (CMAKE_GENERATOR MATCHES "Visual Studio")`, but I figured it's best to just leave it closer to as is.

**Comment by gpx1000** [comment]
I always kept it in Ninja build for Windows as I wanted to ensure the windows build system was using at least NMake.  SCCache was supposed to work with NMake but I never got that working right.  I think it's far better to just bite the bullet and use Ninja as you have here.  I don't think at first blush that the macos build failure in CI is due to the changes here.  lemme know if you need help changing it.
Thanks for the contribution; greatly appreciated!  And great catches of bugs.

**Review by SaschaWillems — APPROVED** [review]
Thank you very much for this PR. Works fine for me on Windows 11 👍🏻

**Review by gpx1000 — APPROVED** [review]
lgtm; thanks for the contribution!

**Review by tomadamatkinson — APPROVED** [review]

**Pull request merged**
