### PR TITLE
Fix msaa sync

### PR DESCRIPTION
**Pull request by Michal-Masiukiewicz-Mobica**
## Description

This PR fixes synchronization errors produced by validation layers in 'msaa' sample.
This sample has few buttons/checkboxes so there are few combinations of states which application can produce.
With this fixes all combinations work (don't produce validation errors).

## Notes:
Tested on:
VulkanSDK: 1.3.239.0
Driver Version: 528.49.0.0
Windows 10
Nvidia Quadro P600
Intel i7-8750H
32 GB RAM

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [ ] My changes build on **Windows**, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Review by gary-sweet — DISMISSED** [review]

**Review by SaschaWillems — DISMISSED** [review]

**Comment by marty-johnson59** [comment]
Hi @Michal-Masiukiewicz-Mobica, looks like the copyright header is stale.  Can you update to 2023?  Thx

**Comment by Michal-Masiukiewicz-Mobica** [comment]
Hi @marty-johnson59 
It seems like this CI check is related to some other change as CI complains about files which I have not modified:

Run python3 /usr/local/bin/check_copyright_headers.py $TARGET_BRANCH
Outdated copyright:
app/CMakeLists.txt
	 Copyright (c) 2019-2022
app/apps/CMakeLists.txt
	 Copyright (c) 2020-2022

Do you know which other commit could modify this files?

**Comment by Michal-Masiukiewicz-Mobica** [comment]
My other review has the same errors:
https://github.com/KhronosGroup/Vulkan-Samples/pull/635
also don't seem to be related to review itself.

**Comment by Michal-Masiukiewicz-Mobica** [comment]
Rebased PR so it would take into account recent changes in repo. This should fix CI.

**Review by gpx1000 — APPROVED** [review]

**Pull request merged**
