### PR TITLE
Update glfw and macOS surface extension

### LINKED ISSUE #327: Can't run on MacOs 11.5.2
With the latest Vulkan SDK on 11.5.2 I am getting the following error.

```
[info] Found GPU: AMD Radeon Pro Vega 56
[error] [framework/platform/glfw_window.cpp:40] GLFW Error (code 65542): Cocoa: Vulkan instance missing VK_EXT_metal_surface extension
[warning] Couldn't find a discrete physical device, picking default GPU
[info] Selected GPU: AMD Radeon Pro Vega 56
[debug] Device supports the following extensions:
```

Updating glfw fixes the issue.

### PR DESCRIPTION
**Pull request by wasimabbas-arm**
## Description

With latest Vulkan SDK and MacOs 11.5.2. The bundled glfw submodule doesn't work anymore. This PR updates it to a later version. In this case to current master, even 3.3-stable doesn't work.

Fixes #327

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Review by SaschaWillems — DISMISSED** [review]
LGTM

**Review by gary-sweet — DISMISSED** [review]

**Comment by TomAtkinsonArm** [comment]
Running `vulkan_samples hello_triangle` on my Macbook Air still crashes. Im using MacOS 11.5.2 and Vulkan SDK 1.2.182.0

**Comment by wasimabbas-arm** [comment]
> Running `vulkan_samples hello_triangle` on my Macbook Air still crashes. Im using MacOS 11.5.2 and Vulkan SDK 1.2.182.0

After some proper investigation this time, I have found the root cause. This isn't to do much with the glfw version but rather the wrong extension used on macOS. I am keeping the glfw version bump as well.

**Comment by TomAtkinsonArm** [comment]
Tested a range of sample with the same setup I described above. Each sample works. The errors shown are related to missing extensions - the window and surface creation now function as expected

**Review by TomAtkinsonArm — DISMISSED** [review]
LGTM

**Review by TomAtkinsonArm — APPROVED** [review]
LGTM, works on Macbook Air

**Review by gary-sweet — APPROVED** [review]

**Pull request merged**
