### PR TITLE
enable performance warnings

### PR DESCRIPTION
**Pull request by samwalls-arm**
## Description

Allows debug callbacks for messages categorised as "perf" (performance warnings, Best Practices etc.)

This means that Best Practice warnings can be emitted from this vulkan application (without this change, they do not appear).

You can try to see performance warnings with the following:
```
export VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation
export VK_LAYER_SETTINGS_PATH=<path-to-my-txt>
```

vk_layer_settings.txt
```
khronos_validation.debug_action=VK_DBG_LAYER_ACTION_LOG_MSG
khronos_validation.report_flags=info,warn,perf,error
khronos_validation.log_filename=stdout
khronos_validation.enables=VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT,VALIDATION_CHECK_ENABLE_VENDOR_SPECIFIC_ARM
```
(or the equivalent in Vulkan-Configurator)

Then run the desired sample.

I look forward to any feedback or advice about this.

Thanks,
Sam Walls

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by SaschaWillems** [comment]
Being able to display these validation layer message types definitely makes sense. But maybe we could enable these using a CMake option instead? Validation layers are already enabled like that using the `VKB_VALIDATION_LAYERS` the option. 

So maybe adding a new CMake option that adds the corresponding flags for the validation messages would be the way to go?

**Comment by samwalls-arm** [comment]
@SaschaWillems Hey, thanks for your reply!

What reasons could there be for making this optional? I'm sure there are some, but I don't know enough to say for sure.

Enabling performance warnings in Khronos' validation layer are, I think, already blocked behind the use of `VK_LAYER_ENABLES=[best-practices-option]:[arm-best-practices-option]`, as well as enabling `perf` warnings etc.. I am cognisant that those are specific to the Khronos VL, though - i.e. I'm not sure how other layers typically handle this.

Adding another switch which blocks them may make it less likely for developers, particularly beginners at cmake, to use them. If we put this behind a switch, could we perhaps set it to `ON` by default?

**Comment by SaschaWillems** [comment]
Yeah, you're right. Just gave this a spin, and hiding these behind an explicit CMake option does indeed make no sense.

**Comment by samwalls-arm** [comment]
Everything I've checked on the checklist I know applies to this issue. Everything left out I'm either unsure if they apply or how to approach checking them off. I'll be attending the next Vulkan Samples call, so hopefully we can discuss this then. 👍

**Review by SaschaWillems — APPROVED** [review]

**Review by gary-sweet — APPROVED** [review]

**Review by gpx1000 — APPROVED** [review]

**Pull request merged**
