### PR TITLE
Add buffer device address sample

### PR DESCRIPTION
**Pull request by HansKristian-Work**
## Description

Adds a sample showing how one can use buffer device addresses. The sample implements a simple scheme where "bindless VBO" is implemented through BDA. The extension is quite abstract to visualize since it just allows for raw pointers, and this was deemed the smallest reasonable sample that can demonstrate why this extension can be useful.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

Tested on RADV, ANV and Arm Mali.

### CODE REVIEW

**Review by gary-sweet — COMMENTED** [review]
Builds ok and correctly reports that the extension is unsupported for Broadcom.
Since I can't test the actual functionality I can't approve it however.

**Comment by SaschaWillems** [comment]
I can't approve, but this LGTM and works as expected on my NVIDIA RTX 2060 (Windows 10).

One minor minor suggestion for the accompanying tutorial: The code blocks should be marked with cpp, so proper language syntax highlighting will be used by using ´´´cpp instead of ```

**Review by aurolou — DISMISSED** [review]

**Review by SaschaWillems — DISMISSED** [review]

**Comment by marty-johnson59** [comment]
@HansKristian-Work, here's another one with some trivial conflicts that need resolving.  @r-potter, can you take a look at this one and approve if OK?  Would like to merge this week if we can.  Thanks!

**Comment by HansKristian-Work** [comment]
@marty-johnson59 I'll resolve the conflicts when we hit 3 approvals. EDIT: Actually, it doesn't matter either way, I'll just resolve it now.

**Comment by HansKristian-Work** [comment]
@marty-johnson59 Good to go when 1 more reviewer approves.

**Comment by marty-johnson59** [comment]
@AlejandroCosin, @carlosadcq can you guys check out this one to see if it's OK?  Trying to merge this one shortly to support some blogs going out.  Thanks!

**Review by gpx1000 — APPROVED** [review]

**Comment by HansKristian-Work** [comment]
@marty-johnson59 Got 3 approvals now.

**Review by SaschaWillems — APPROVED** [review]

**Pull request merged**
