### PR TITLE
Add 16-bit storage InputOutput performance sample

### PR DESCRIPTION
**Pull request by HansKristian-Work**
## Description

This performance sample demonstrates the bandwidth savings you can achieve on some TBDR architectures when using StorageInputOutput16. It does not modify common framework code.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

I've tested build on Linux and Android, don't have an easy setup to test Windows/macOS build atm. Regressions are not relevant as it doesn't touch other samples. There is no common framework code that warrants Doxygen.

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

I have tagged the sample as "Arm", but other IHVs might benefit. If so, I can remove the tag. Tested on NVIDIA, AMD (RADV ACO) and Arm Mali.

### CODE REVIEW

**Review by wasimabbas-arm — DISMISSED** [review]

**Review by gary-sweet — DISMISSED** [review]
Builds and runs fine for Broadcom (though 16-bit is not supported).
I note there is still a CI check that is failing however.

**Comment by HansKristian-Work** [comment]
@gary-sweet @wasimabbas-arm Fixed clang formatting check, please re-approve.

**Review by wasimabbas-arm — DISMISSED** [review]

**Review by gary-sweet — COMMENTED** [review]
The clang-format changes look fine.
Since I can't actually test the new functionality here, I'll leave it to those who can to approve.

**Comment by marty-johnson59** [comment]
@aurolou Hi Lou, can you review this sample from a DT standpoint?  Would like to verify this on DT before merging.  Thanks!

**Comment by aurolou** [comment]
sure, I have a look!

**Comment by marty-johnson59** [comment]
@r-potter,  @mattruschnv, hi guys, we'd like to get this one merged soon, but need 3 reviews.  Lou agreed to look at it.  Can you guys take a loo too?  LMK, thx,

mcj

**Review by r-potter — CHANGES_REQUESTED** [review]
Tested on both Mali and Adreno Note10s. 

The sample itself has no issues, but should it be listed as an Extension sample rather than a Performance sample? Everything else under Performance is core API stuff. 

I'm otherwise happy to merge this once the group decides on the question above.

**Review by r-potter — DISMISSED** [review]

**Comment by marty-johnson59** [comment]
Can we get one more review on this one so we can merge?  Thanks!
@aurolou, @gary-sweet, @JoseEmilio-ARM, @ZandroFargnoli, @mattruschnv, @AlejandroCosin, @carlosadcq

**Comment by marty-johnson59** [comment]
Can we get one more review on this one so we can merge?  Thanks!
@aurolou, @gary-sweet, @JoseEmilio-ARM, @ZandroFargnoli, @mattruschnv, @AlejandroCosin, @carlosadcq

**Comment by carlosadcq** [comment]
I tested on Adreno, the sample runs and marks the VK_KHR_16bit_storage extension as 'noop - unsupported' but it is actually supported and listed when device lists out all the extensions supported by the device. I'm not sure yet as to why this is happening since I haven't been able to review the code yet.

**Comment by HansKristian-Work** [comment]
@carlosadcq 16-bit InputOutput feature is probably not supported in that case, it's not just the extension that needs to be supported.

**Comment by SaschaWillems** [comment]
I can't approve, but this LGTM and works as expected on my NVIDIA RTX 2060 (Windows 10).

One minor minor suggestion for the accompanying tutorial: The code blocks should be marked with cpp, so proper language syntax highlighting will be used by using ´´´cpp instead of ```

**Review by SaschaWillems — DISMISSED** [review]

**Comment by marty-johnson59** [comment]
@HansKristian-Work, can you check out the minor conflicts above and resolve?  Then we should be OK to merge this one.  Thx,

mcj

**Comment by marty-johnson59** [comment]
@HansKristian-Work can you resolve these ones too so I can merge?  Thanks

**Comment by HansKristian-Work** [comment]
@marty-johnson59 resolved

**Pull request merged**
