### PR TITLE
Proper compute n-body sample synchronization

### LINKED ISSUE #3: Missing queue family ownership transfer in compute_nbody
The `compute_nbody` sample seems to be missing a queue family ownership transfer of `compute.storage_buffer` on platforms where a compute-only queue family is available.

Note how `compute.storage_buffer` is used as a storage buffer in `compute.queue` and as as vertex buffer in `queue`, and consider the following:
- If the platform has a compute only queue family available, it will be preferred.
    - The compute dispatches use the  `compute.queue` queue: https://github.com/KhronosGroup/Vulkan-Samples/blob/55abaaea0ca34288045cd52093cb1060b891508a/samples/api/compute_nbody/compute_nbody.cpp#L629
   - `compute.queue` is set here: https://github.com/KhronosGroup/Vulkan-Samples/blob/55abaaea0ca34288045cd52093cb1060b891508a/samples/api/compute_nbody/compute_nbody.cpp#L437
   - The logic in `Device::get_queue_family_index(VkQueueFlagBits queue_flag)` will pick a queue family with compute and no graphics if available; https://github.com/KhronosGroup/Vulkan-Samples/blob/55abaaea0ca34288045cd52093cb1060b891508a/framework/core/device.cpp#L349
    - **On my Radeon RX 590 queue family index 1 is picked here**
- The default `queue`'s queue family is the first one available which supports presentation:
   - It's created here https://github.com/KhronosGroup/Vulkan-Samples/blob/55abaaea0ca34288045cd52093cb1060b891508a/framework/api_vulkan_sample.cpp#L57
   - This calls `Device::get_queue_by_present` which picks the first queue family which can present; https://github.com/KhronosGroup/Vulkan-Samples/blob/55abaaea0ca34288045cd52093cb1060b891508a/framework/core/device.cpp#L328
    - **On my Radeon RX 590 queue family index 0 is picked here**
- `compute.storage_buffer` is created with `VK_SHARING_MODE_EXCLUSIVE`; see https://github.com/KhronosGroup/Vulkan-Samples/blob/55abaaea0ca34288045cd52093cb1060b891508a/framework/core/buffer.cpp#L32

In other words, `compute.queue` and `queue` can be from different queue families (and _is_ on my system), which means `compute.storage_buffer` can not be shared between the two queues without having the queue family ownership transferred:
```Resources created with a VkSharingMode of VK_SHARING_MODE_EXCLUSIVE must have their ownership explicitly transferred from one queue family to another in order to access their content in a well defined manner on a queue in a different queue family```

The problem is the sample is missing pipeline-barriers to perform this ownership transfer currently. As such, the sample is only correct on systems where the code happens to pick the queues so they are from the same queue family.

### PR DESCRIPTION
**Pull request by SaschaWillems**
## Description

This PR adds proper synchronization to the compute N-Body sample for implementations with separate graphics and compute queues. Fixes #3.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- n/a I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- n/a I have used existing framework/helper functions where possible
- [x] My changes build and run on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)

### CODE REVIEW

**Review by gary-sweet — COMMENTED** [review]
This doesn't break anything for me, but I don't have separate compute and graphics queue families so can't  test the new code.

**Review by ZandroFargnoli — APPROVED** [review]
LGTM

**Review by aurolou — APPROVED** [review]

**Comment by mattruschnv** [comment]
I'm still not able to build this. The third approval will need to come from someone other than me.

**Comment by SaschaWillems** [comment]
Sorry to hear Matt. I just checked this with a clean new system and I could compile it without problems, but I can imagine that this once again may be caused by some submodule not properly getting updated.

**Comment by mattruschnv** [comment]
It's likely user error on my part. Let me take another look.

**Comment by mattruschnv** [comment]
Yep, my fault. Looks good to me now.

**Review by mattruschnv — APPROVED** [review]

**Pull request merged**
