### PR TITLE
Explicitily set window focus

### LINKED ISSUE #399: Some samples won't properly update/render after starting in release mode
While testing the samples in release mode, I noticed some of the samples no longer properly rendering after starting them. E.g. the AFBC sample shows the first frame, and upon resize it's not updated and does not show the expected animation:

image
(white border = initial window size after startup, black border appears in the resized area of the window)

Resizing the window multiple times make the sample work as expected.

This is on Windows 10 and happens on two completely different machines .One with an Nvidia RTX 2060 with the public 472.69 Vulkan Developer drivers and one with an Intel UHD 630 iGPU.

This does only seem to happen in release builds and mostly with samples that load more complex assets. So this could be a timing issue or may be caused by not properly initialized variables.

### PR DESCRIPTION
**Pull request by TomAtkinsonArm**
## Description

Explicitly set window focus to true so that the application begins rendering on start.

Currently the first frame renders but rendering is then halted until the window is perceived as focused again. For GLFW this takes multiple resizes or min/maximizing the window. Setting focus to true to begin with resolves this issue for me

Fixes #399 

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by TomAtkinsonArm** [comment]
@SaschaWillems can you check if this resolves the initial issue?

If it works it may be a better fix to force GLFW to focus the window on creation

**Comment by SaschaWillems** [comment]
This does indeed fix my issue. I can no longer reproduce the bug mentioned in #399 :)

**Review by gpx1000 — APPROVED** [review]

**Review by SaschaWillems — APPROVED** [review]

**Comment by MattGuerrette** [comment]
Unfortunately this will not solve situations where the application will lose focus explicitly on launch. For example, when running these samples using the [Radeon Developer Panel](https://github.com/GPUOpen-Tools/radeon_developer_panel), the samples cannot be captured unless the sample app regains focus as the panel will focus itself to the top level when a client application (Vulkan app or DX12 app) connects, stealing the focus from the samples.

Could there be a build option or runtime option implemented that removes entirely the check for application focus?

**Comment by TomAtkinsonArm** [comment]
@MattGuerrette I agree, the current implementation doesn't work well with what the samples is trying to achieve. Especially when considering the developer tools use case.

If I recall correctly, stopping rendering when loosing focus was implemented so that in demos phones has a chance to cool down in between long runs without having to close the app. Closing the app would mean we need to wait for assets to re load etc.

That said, it makes sense to allow the user to decide what "optimizations" should be used. I prefer runtime options over compile time options especially when it is something as small as this. Let me see if I can add a quick plugin to toggle this

**Comment by TomAtkinsonArm** [comment]
Interesting, I also needed to bump Volk and Vulkan headers to 1.2.198 to build on windows on my intel laptop... This has not been caught in the CI

**Comment by pdaniell-nv** [comment]
I've noticed this same problem with the latest Khronos sample code. Any chance we can get this fix merged soon?

**Review by gary-sweet — APPROVED** [review]
Looks fine to me, but I note that there are still some unaddressed comments.

**Pull request merged**
