### PR TITLE
Fix hlsl for ray tracing samples.

### PR DESCRIPTION
**Pull request by gpx1000**
Fix the build for hlsl in ray tracing samples.  They require SPV_KHR_ray_query extension be set in order to build.

### CODE REVIEW

**Comment by SaschaWillems** [comment]
Not sure about removing the precompiled shader files. We deliberately added them so people that don't have access to DXC can still run our samples. We wan't to do the same with GLSL shaders once we have offline compilation up and running.

**Comment by gpx1000** [comment]
Hmmm.  We should probably create a cmake rule to not touch them unless their shaders have changed and dxc is detected then.  Otherwise git is going to think they need updating when they don't

**Comment by SaschaWillems** [comment]
Yeah, that's correct. I actually though that was the case with Mobica's PR that added DXC compilation :/

**Comment by gpx1000** [comment]
Okay, I'll try to craft something for this PR that handles it then.

**Comment by gpx1000** [comment]
I switched it from a function call to cmake tasks so cmake correctly will detect when updates to the shader source code should have a shader recompiled.   We might also setup a find_dxc.cmake package file so this more generic solution could be found anywhere and allow for a compile SPIR-V function for cmake that can be packaged with DXC.

**Review by SaschaWillems — APPROVED** [review]

**Review by gary-sweet — APPROVED** [review]

**Comment by marty-johnson59** [comment]
I'll merge this on 2 approvals as it prevents running the Batch script...LMK if we need to revert

**Pull request merged**
