### PR TITLE
CI Fixes

### PR DESCRIPTION
**Pull request by tomadamatkinson**
# Description

There have been a few PRs lately attempting to fix issues in the CI. Most solve the issues but then the CI breaks in some other obscure way. Here I have attempted to do a pass over the CI and make some quality of life improvements whilst I was at it.

### Doxygen Check
- Reduced to 10-20s from 1-5m
- Uses [ghcr.io/khronosgroupactions/doxygen:1.9.5](https://github.com/KhronosGroupActions/doxygen/pkgs/container/doxygen)

### Copyright Check
- Reduced to 10-20s from 1-5m
- Uses [ghcr.io/khronosgroupactions/copyright-check:latest](https://github.com/KhronosGroupActions/copyright-check/pkgs/container/copyright-check)

### Snake Case Check
- Reduced to 10-20s from 1-5m
- Uses [ghcr.io/khronosgroupactions/snake-case-check:latest](https://github.com/KhronosGroupActions/snake-case-check/pkgs/container/snake-case-check)

### Clang Format and Clang Tidy
- Updated to 15.0.6
- Uses [ghcr.io/khronosgroupactions/clang-tools:15.0.0](https://github.com/KhronosGroupActions/clang-tools/pkgs/container/clang-tools)
- Reduced Image Size improves checkout speed
- Use scripts supplied by `clang-extra-tools` as these are more up to date than those in this project

### Android Build
- Moved Android build to a different image
- Uses [ghcr.io/khronosgroupactions/android-ndk-build:r25b](https://github.com/KhronosGroupActions/android-ndk-build/pkgs/container/android-ndk-build)
- Image now builds in 4 minutes instead of 30min-1hour
- Image is now 4GB instead of 7GB+

# Known Issues
- `git config --global --add safe.directory /__w/Vulkan-Samples/Vulkan-Samples` is sometimes required
  - This should be handled by `actions/checkout@v3` but seems to intermittently fail

### CODE REVIEW

**Comment by tomadamatkinson** [comment]
@ggfan for some reason I can't add you to the reviewer list, please take a look at this when you get chance :)

This still requires your validation layer fix

**Review by ggfan — APPROVED** [review]
The Android Build part looks good: assembleDebug is the command to use.

**Comment by marty-johnson59** [comment]
Just seeing the one CI failure on Clang Tidy Check.  We discussed this on the Samples call and just need guidance from @tomadamatkinson if we're OK merging this with this failure (external warnings).  LMK as this one will fix several other CI failures.  Thx

**Comment by ggfan** [comment]
LGTM, thank you so much!

**Review by ggfan — APPROVED** [review]

**Comment by marty-johnson59** [comment]
OK, I'll go ahead and merge this.  LMK if it causes issues and I can revert.  Thanks!

**Pull request merged**
