### PR TITLE
Fixes queue type in texture_compression_comparison tests

### PR DESCRIPTION
**Pull request by mnetsch**
Queue type was VK_QUEUE_TRANSFER_BIT, but this is optionally
supported as a separate queue type from graphics and compute.

## Description

Please include a summary of the change, new sample or fixed issue. Please also include relevant motivation and context.
Please read the [contribution guidelines](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md)

Fixes #<issue number>

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by mnetsch** [comment]
How should the copywrite be handled for this case?

**Comment by mnetsch** [comment]
@KhronosGroup/vulkan-samples-reviewers

**Comment by SaschaWillems** [comment]
We don't have a clear guideline on copyrights. But for such small changes, it be enough to just update the date in the files you changed. Judging by the failed CI step, you only need to change the "Copyright (c) 2021..." to "Copyright (c) 2021-2022..." and CI should be fine.

**Comment by mnetsch** [comment]
Thanks

**Review by SaschaWillems — APPROVED** [review]
LGTM.

**Review by gary-sweet — APPROVED** [review]

**Review by gpx1000 — APPROVED** [review]

**Pull request merged**
