### PR TITLE
Fix docker build

### PR DESCRIPTION
**Pull request by gpx1000**
## Description

simply working on fixing docker image build.

### CODE REVIEW

**Review by ggfan — APPROVED** [review]
This is needed to update the NDK / CMake version used by CI, thank you for helping!

**Comment by TomAtkinsonArm** [comment]
@gpx1000 this seems to have lots more commits in the log? but only one change?

**Comment by gpx1000** [comment]
Yeah, my fault.  I made the branch off of my fork's master which was out of date when I made it.   I tried merging but it still winds up listing all of the commit changes.  There is only one change despite the log getting messed up.  If this is a concern I can recreate a new branch based upon main and it should only have the one commit.

**Comment by TomAtkinsonArm** [comment]
Although it shouldn't be an issue to squash and merge this PR, it would be better if there was only one commit from the main branch

**Comment by gpx1000** [comment]
Yeah, I kinda agree.  Do you want me to create a new branch to clean it?  Just lemme know.  The change should literally be one character ;-)

**Comment by TomAtkinsonArm** [comment]
Please, I would do it but it's your change, and I don't want to steal the commit :)

**Pull request closed without merging**
