### PR TITLE
Refactor API sample hpp_hello_triangle

### PR DESCRIPTION
**Pull request by asuessenbach**
## Description

Includes adjustments in `common/hpp_vk_common.h` and in API samples `hpp_compute_nbody`, `hpp_dynamic_uniform_buffers`, and `hpp_hdr`.

Builds and runs on Win10 on NVidia HW.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Review by gpx1000 — APPROVED** [review]

**Review by gary-sweet — APPROVED** [review]

**Review by r2d2Proton — COMMENTED** [review]
Regarding pull request 680, refactoring the API sample hpp_hello_triangle, there are changes to the framework, in addition to the sample itself.
Forgive me I do not know what is expected and decided upon (if anything). Is that public and open to view too?
Speaking specifically to the framework, as in shared among others, create_descriptor_set_layout is deleted, along with create_descriptor_pool.
Are these on purpose?
My standard disclaimer applies, take what I say with a grain of salt: I just starting with the Vulkan API, and behind the curve at the moment.

**Comment by SaschaWillems** [comment]
The removed function you mentioned are simply not needed because they're already available elsewhere, e.g. directly in Vulkan.hpp.

**Review by SaschaWillems — APPROVED** [review]
LGTM

**Comment by r2d2Proton** [comment]
Out of curiosity, do the automated tests catch deleted functions? Specifically, a sample that references a function in framework?

**Comment by SaschaWillems** [comment]
Yes, CI builds all samples on all platforms. So any reference to deleted stuff will make the CI fail.

**Comment by tomadamatkinson** [comment]
> Out of curiosity, do the automated tests catch deleted functions? Specifically, a sample that references a function in framework?

@r2d2Proton we catch compile time failures but we have no mechanism for runtime tests at this time. There are some efforts to improve this though

**Comment by tomadamatkinson** [comment]
Merging on three approvals

**Pull request merged**
