### PR TITLE
Place the binary ktx shared library in the same directory as the executable

### PR DESCRIPTION
**Pull request by gpx1000**
## Description

@tomadamatkinson See if you like option 2 better.  Also, it's worth pointing out that app/CMakeLists.txt line 80 is really where a fix will likely work.  It's also the probable reason why it just doesn't work out of the box from CMake's default settings.

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by tomadamatkinson** [comment]
I'm skeptical that this will work out of the box on android compared to the static library. Have you been able to test running on a device?

I don't mind which approach we use. We just need to pick one soon so that samples can run on windows

**Comment by asuessenbach** [comment]
Unfortunately, the ktx.dll does not materialize where it should be.

I assume, that `$<TARGET_PROPERTY:vulkan_samples,RUNTIME_OUTPUT_DIRECTORY>` is supposed to be evaluated to a directory from the vulkan_samples project.
But when I get the ktx-property right after setting it
```
get_target_property(lod ktx LIBRARY_OUTPUT_DIRECTORY)
message(STATUS "lod = ${lod}")
```
this is what I get:
`lod = C:/git/Vulkan-Samples/build/VS2022_64/app/$<TARGET_PROPERTY:vulkan_samples,RUNTIME_OUTPUT_DIRECTORY>
`

**Comment by marty-johnson59** [comment]
Hi @gpx1000, there was some question on today's call about weather this is still needed given other recent changes.  LMK if we can close.  Thx.

**Comment by marty-johnson59** [comment]
no longer needed

**Pull request closed without merging**
