### PR TITLE
Virtual File System

### LINKED ISSUE #432: FI: Virtual File System
**What is the Problem?**

The framework has a filesystem implementation. The main issue with the implementation is its readability. Its original design did not fit well with the Android platform and so over time `Platform` needed to add methods to determine asset and temp directories. This was a hot fix to allow android to push these strings from java to cpp. AAssetManager is taken from the gltf third party causing more issues. There are lots of platform specific implementations for filesystem code and no mechanism to mount different filesystems to different paths.

Although cpp2017 has a better file system abstraction it is not yet feasible to use in samples due to Android support.

**What is the proposed Solution?**

It is common in frameworks to have a virtual filesystem. I propose using a common "mounting" mechanism to layer filesystems of different types into the same object which is used by other APIs in the project.

**Examples**

Example API usage.

```cpp
FileSystem fs;
fs.mount("/some/asset/dir", SomeFileSystemImplementation());
fs.mount("/some/temp/dir", OsSpecificTempImplementation());
fs.mount("/android/assets", AAssetManagerFileSystem());
fs.mount("/android/temp", AndroidTempImplementation());


auto status = fs.read_file("/some/asset/dir/sponza.gltf", &out_data)
```

**Issues**

We do not have access to std paths. This means a standard for paths should be used. A sufficient standard may look like this `/this/is/a/file/path.txt`

All areas of the project would need to use the new file system abstraction.

### PR DESCRIPTION
**Pull request by TomAtkinsonArm**
## Description

Virtual File System implementation to replace the frameworks filesystem implementation.

- Adds Android Sync/Bundle variants. Sync classic push files, Bundle packages assets within the apk
- Uses #447 android changes - required for a correct android builds
- Replaces all file usage in the framework with vfs

This PR should stand as an example for how future framework rewrites will be carried out. Each component removed from the framework should live in its own `components/<component>` directory. From here the minimum amount of functionality providing the most value should be extracted. For example in this PR i have not re implemented many of the original filesystems functions. This is an effort to simplify the code base whilst refactoring.

See #432 for a more abstract overview for why this change is needed

Fixes #432

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

### CODE REVIEW

**Comment by TomAtkinsonArm** [comment]
@asuessenbach I cant seem to add you as a reviewer but it would be great to get your opinion on this PR

**Review by gary-sweet — APPROVED** [review]
Seems like a good approach to me. No problems building or running.

**Review by gpx1000 — APPROVED** [review]
Finally got around to testing/running this.  LGTM!

**Comment by TomAtkinsonArm** [comment]
Thank you both for the reviews!

Just a reminder when we come to discuss this later. #447 must merge before this. I needed to re-base on this PR as I could not get android to build OOB without it

**Pull request closed without merging**
