### PR TITLE
Add shaders to the project structure

### LINKED ISSUE #335: Add shaders to Visual Studio solution
On the last call, we discussed adding shaders to the Visual Studio solution file. This makes it easy to open shaders directly from the IDE and see what shaders belong to a given example.

We discussed this some time ago on https://github.com/KhronosGroup/Vulkan-Samples/pull/197.

### PR DESCRIPTION
**Pull request by SaschaWillems**
## Description

This PR adds the GLSL shader files to the project structure. So for IDEs like Visual Studio you can now see what shaders belong to a given sample and open them directly in your IDE, without having to search for them on the disk.

The solution in this new PR differs from the one in #197 and is more explicit. #197 used CMAKE's GLOB and worked only for samples where the shaders resided in a folder named exactly like the sample. Smaples differing from that would not have the shaders added to the project structure.

This PR explicitly adds all shaders to the samples' CMake files, e.g.:

```cmake
add_sample_with_tags(
    ID ${FOLDER_NAME}
    FILES ${GLSL_FILES}
    CATEGORY ${CATEGORY_NAME}
    AUTHOR "Martin-Karl Lefrançois"
    NAME "Ray tracing reflection"
    DESCRIPTION "Example for hardware accelerated ray tracing"
    SHADER_FILES_GLSL
        "ray_tracing_reflection/raygen.rgen"
        "ray_tracing_reflection/miss.rmiss"
        "ray_tracing_reflection/missShadow.rmiss"
        "ray_tracing_reflection/closesthit.rchit")
```

Resulting in this:

image

Fixes #335

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

### CODE REVIEW

**Review by TomAtkinsonArm — DISMISSED** [review]
LGTM

**Review by gary-sweet — DISMISSED** [review]

**Review by gpx1000 — DISMISSED** [review]
LGTM

**Comment by SaschaWillems** [comment]
I have rebased this on master. Any (re)review would be appreciated :)

**Review by TomAtkinsonArm — APPROVED** [review]

**Review by gpx1000 — APPROVED** [review]
LGTM

**Review by gary-sweet — APPROVED** [review]

**Comment by TomAtkinsonArm** [comment]
@marty-johnson59 this is ready

**Pull request merged**
