### PR TITLE
Update Vulkan Headers to 1.3.204

### PR DESCRIPTION
**Pull request by SaschaWillems**
## Description

This PR updates the Vulkan Headers to version 1.3.204

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

### CODE REVIEW

**Comment by SaschaWillems** [comment]
It looks like updating to Vulkan 1.3 broke several vulkan.hpp related units. @asuessenbach: can you take a look at that? I'm not sure what changed with 1.3 in vulkan.hpp that suddenly breaks the build on all platforms.

It seems that some C++ Types can no longer be converted to their C counterparts, e.g.:

```cpp
/Vulkan-Samples/Vulkan-Samples/framework/core/hpp_queue.h:43:54: error: no viable conversion from 'const vk::PresentInfoKHR' to 'const VkPresentInfoKHR'
                return static_cast<vk::Result>(vkb::Queue::present(present_infos));
```

**Comment by SaschaWillems** [comment]
I'm also having troubles compiling this on my machine at all with MSVC. At some point it consumes all of my RAM and then just stalls the system. My other projects that are on Vulkan 1.3 but don't use vulkan.hpp work fine, so I expect something to be wrong with the hpp header in general.

**Comment by asuessenbach** [comment]
With Vulkan-Headers version 202, I changed the cast operators in vulkan_structs.hpp to be explicit, to catch inadvertent mix-and-match.
And I did miss some of those casts in the samples here. Sorry about that.
With #418, those errors should be resolved.

Regarding the build issue with MSVC: I can't see such behaviour on my end. No idea what might be wrong there.

**Comment by SaschaWillems** [comment]
No need to be sorry. Thank you very much for fixing this :)

Will see if the build error due to insufficient memory still happens with your PR and 1.3.

**Comment by SaschaWillems** [comment]
This is a very odd problem. I've been able to pinpoint this to the plugins part of the framework. With headers updated to Vulkan 1.3, as soon as I try to build the plugins library and e.g. the windows_options plugin is about to compile, msvc chews up all of my memory including swap until my system is no longer reponsive. Removing some of the plugins from the build helps, but that's not an actual solution.

If I downgrade to headers 1.2 everything is fine again.

This is with the latest Version of Visual Studio 2019. @TomAtkinsonArm: Do you have an idea why this is happening? It's stopping me from updating headers to 1.3 required for my next sample :(

**Review by gary-sweet — APPROVED** [review]
Works fine for me on Linux

**Review by TomAtkinsonArm — APPROVED** [review]
Build locally for me.

@SaschaWillems I cant find the issue your referencing? Are you building the project in a specific way?

**Review by gpx1000 — APPROVED** [review]

**Pull request merged**
