### PR TITLE
Fix build error of ‘exchange’ is not a member of ‘std’

### LINKED ISSUE #1010: Linux build error of ‘exchange’ is not a member of ‘std’
```
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
```
```
Vulkan-Samples/framework/core/vulkan_resource.h: In constructor ‘vkb::core::VulkanResource<THandle, Device>::VulkanResource(vkb::core::VulkanResource<THandle, Device>&&)’:
Vulkan-Samples/framework/core/vulkan_resource.h:102:25: error: ‘exchange’ is not a member of ‘std’
  102 |             handle(std::exchange(other.handle, VK_NULL_HANDLE)),
      |                         ^~~~~~~~
```

### PR DESCRIPTION
**Pull request by zzyiwei**
Fixes #1010

### CODE REVIEW

**Comment by zzyiwei** [comment]
@SaschaWillems Hi Sascha, do you have some time to review this tiny fix? thx in advance!

**Comment by SaschaWillems** [comment]
I'm not the sole reviewer, but I'll try to a take a look this weekend.

**Review by gpx1000 — APPROVED** [review]

**Review by SaschaWillems — APPROVED** [review]

**Review by spencer-lunarg — APPROVED** [review]
hit same issue with clang-15, confirmed this worked for me!

**Comment by zzyiwei** [comment]
Looks to be already fixed by https://github.com/KhronosGroup/Vulkan-Samples/pull/984 merged a few hours ago.

**Pull request closed without merging**
