### PR TITLE
Add Python Scripts 

### LINKED ISSUE #712: Use Python for build scripts
Currently there are 2 different languages used for the build scripts (batch and bash). There are some problems with these languages that Python can solve, for example requiring a script be run from a certain directory for correct behaviour.

### PR DESCRIPTION
**Pull request by tomadamatkinson**
## Description

Cleans up some of our outdated scripts and re-implements their behaviour in python scripts as suggested in #712 
Added a README for some extra clarity
Moved outside of `bldsys` so that they are more obvious to users - after all they are not build related

The Copyright check script has been updated to support more formats and I added a handy `--fix` option where the script can automatically update outdated copyrights - no more `"find file" -> "update copyright" -> "run CI"`

The docker file has been slimmed down to only include what it needs. Most of the scripts in this file where moved to their respective action in `KhronosGroupActions` at the start of the year. I have not updated the `vulkan_samples` package with this new image as the original image will work fine for now

Removed the 

Fixes #712 

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Review by gpx1000 — DISMISSED** [review]

**Review by SaschaWillems — CHANGES_REQUESTED** [review]
With PR#635 we added a way of generating samples based on the api sample class. I no longer see a way of doing this with the new generate.py script.

With the old script you could explicitly either create a sample based on the ARM framework or my API class via the `template` argument:

```.\generate_sample.bat Dummy api sample_api```

I don't see a way of doing this with the new python script.

**Comment by tomadamatkinson** [comment]
> With PR#635 we added a way of generating samples based on the api sample class. I no longer see a way of doing this with the new generate.py script.
> 
> 
> 
> With the old script you could explicitly either create a sample based on the ARM framework or my API class via the `template` argument:
> 
> 
> 
> ```.\generate_sample.bat Dummy api sample_api```
> 
> 
> 
> I don't see a way of doing this with the new python script.

You can do this with the --template option

./generate.py --template sample_api

However this is not well documented in this PR. I shall update the docs to fix this

**Comment by tomadamatkinson** [comment]
@SaschaWillems made the api sample template stand out more by adding a new command `./scripts/generate.py sample_api`

**Comment by SaschaWillems** [comment]
Perfect 👍 

But the help command is still lacking some arguments:

```
usage: generate.py [-h] {android,sample,sample_api} ...

Generate utility.

positional arguments:
  {android,sample,sample_api}
                        Commands
    android             Generate Android Gradle files
    sample              Generate sample project
    sample_api          Generate sample project

options:
  -h, --help            show this help message and exit
```

There is no notion of `--name`, `--category` and `--output-dir`. I think we should also remove default values for name and categroy.

**Comment by SaschaWillems** [comment]
And maybe a better command line help in general? How do I combine android and sample_api? Why do we have the android argument at all? 

Sorry for asking those questions, but I just want this stuff to be as easy to use as possible ;)

**Comment by tomadamatkinson** [comment]
Hey @SaschaWillems, no need to apologise this is what the review process is for! Thank you for the feedback and the fast responses

`android`, `sample_api` and `sample` are commands. These can not be used together. Similar to `gh` the Github CLI, you can not use `gh repo` and `gh auth` at the same time. This is also a pattern we use in the vulkan samples cli - `samples` to list samples vs `sample` to run a specific sample. Although `vulkan_samples run <app_name>` might make more sense :)

If you run `./script/generate.py sample -h` this will show command specific help. I agree that is not obvious from the default `argparse` help message. However it is similar in other CLIs.

```
❯ ./scripts/generate.py sample -h
usage: generate.py sample [-h] [--name NAME] [--category CATEGORY] [--output-dir OUTPUT_DIR]

options:
  -h, --help            show this help message and exit
  --name NAME           Name of the sample project
  --category CATEGORY   Which category the sample project belongs to
  --output-dir OUTPUT_DIR
                        Output Directory: <project_dir>/samples/<category>
```

I have provided a readme which explains the intended usage of the scripts and hopefully this would be enough guidance for users? See `scripts/README.md`

**Review by SaschaWillems — APPROVED** [review]

**Review by gpx1000 — APPROVED** [review]

**Comment by tomadamatkinson** [comment]
Merging on 2. Does not affect samples or the code base. Helps improve the quality of life of those developing in the repo

**Comment by milijunjin** [comment]
> Perfect 👍
> 
> But the help command is still lacking some arguments:
> 
> ```
> usage: generate.py [-h] {android,sample,sample_api} ...
> 
> Generate utility.
> 
> positional arguments:
>   {android,sample,sample_api}
>                         Commands
>     android             Generate Android Gradle files
>     sample              Generate sample project
>     sample_api          Generate sample project
> 
> options:
>   -h, --help            show this help message and exit
> ```
> 
> There is no notion of `--name`, `--category` and `--output-dir`. I think we should also remove default values for name and categroy.

hi SaschaWillems, when i run into an issue when enter ./scripts/generate.py sample --name mysample,that is "Missing cmake
", could you kindly help me check why this error happen?

**Comment by tomadamatkinson** [comment]
Hey @milijunjin, do you have cmake accessible via your PATH? The scripts dependencies must be accessible via the command line's environment

**Comment by milijunjin** [comment]
> 

thanks for your reply, how can i checki have cmake access?

**Comment by milijunjin** [comment]
thanks for your reply, how can i check i  have cmake access? @tomadamatkinson

**Comment by SaschaWillems** [comment]
Open a terminal/command line and try to run "cmake" from there. If that doesn't work, cmake is either not installed or not in your path.

**Comment by milijunjin** [comment]
@SaschaWillems hi SaschaWillems, glad to see your reply, it works now, i generate my android sample successfully, the next step is to buid an apk ,right? then use the gfx tool to capture trace?  could i use normal popular release game to replace the sample, then capture trace? or i have to build the debug apk for capturing the trace?

**Comment by milijunjin** [comment]
@tomadamatkinson  @SaschaWillems  Hey, two gentlemen, i finally built the vulkan sample successfully, but when i launch it on the phone, click any section such as "Hello Triangle","AFBC" and so on, the app quit, i found below error in logcat:

failed to load layer library '/vendor/lib64/libVkLayer_mtk_rt_sdk.so': dlopen failed: library "/vendor/lib64/libVkLayer_mtk_rt_sdk.so" needed or dlopened by "/apex/com.android.art/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"


could you kindly help me check why it happened, i have no idea about it.

**Pull request merged**
