### PR TITLE
Fix all child nodes are added to scene root

### PR DESCRIPTION
**Pull request by Chaphlagical**
## Description

Please include a summary of the change, new sample or fixed issue. Please also include relevant motivation and context.
Please read the [contribution guidelines](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md)

Fixes gltl_loader will add all nodes as scene root's children.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

### CODE REVIEW

**Comment by marty-johnson59** [comment]
Reviewers added.  @Chaphlagical, can you update the copyright first before getting all the approvals (so we can pass all the CI tests)?  That makes the process much smoother.  Thanks

**Comment by Chaphlagical** [comment]
> Reviewers added. @Chaphlagical, can you update the copyright first before getting all the approvals (so we can pass all the CI tests)? That makes the process much smoother. Thanks

ok

**Review by DiamondHold — CHANGES_REQUESTED** [review]
Wrong account 😅 commented below !

**Review by ZandroFargnoli — CHANGES_REQUESTED** [review]
Hi @Chaphlagical, nice spot! We must of missed this due to all the assets using flat hierarchies. 

I pushed the same fix a few months ago to a private fork, but I also had to reverse the order of multiplication for our transforms - we were multiplying the `Child * Parent` where as we need to be doing `Parent * Child`. 

Can you confirm for me this works for glTF files that use node hierarchies (such as the glTF 2.0 Lantern asset found [here](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Lantern))?

Inside our [transform.cpp](https://github.com/KhronosGroup/Vulkan-Samples/blob/6e9c35bf19164c10392f24287364ba7e8206d5f8/framework/scene_graph/components/transform.cpp#L125) we currently do:
```
world_matrix    = world_matrix * transform.get_world_matrix();
```
That should be changed to:
```
world_matrix    = transform.get_world_matrix() * world_matrix;
```

This branch give me the following results:

image

And changing the order of multiplication inside transform.cpp gives:

image

Thanks!

**Comment by Chaphlagical** [comment]
Hi @ZandroFargnoli, it should be
```
world_matrix    = transform.get_world_matrix() * world_matrix;
```

**Review by ZandroFargnoli — APPROVED** [review]
LGTM! Thank you @Chaphlagical

**Review by SaschaWillems — APPROVED** [review]

**Review by gary-sweet — APPROVED** [review]

**Review by gpx1000 — APPROVED** [review]

**Pull request merged**
