### PR TITLE
Fix tmax in the ray_queries sample

### PR DESCRIPTION
**Pull request by KonstantinSeurer**
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#ray-intersection-candidate-determination:

We need to set tmax to 1 because the length of direction already accounts for the distance to the light.

### CODE REVIEW

**Comment by JoseEmilio-ARM** [comment]
> https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#ray-intersection-candidate-determination:
> 
> We need to set tmax to 1 because the length of direction already accounts for the distance to the light.

Thanks for pointing this out! However, not sure I follow, is `tmax = 1` a special case? Could you please quote the part of the spec that you are referring to? In this case, we are using ray query with `gl_RayFlagsTerminateOnFirstHitEXT`, so do not really need to track `tmax`. I agree than rather than `distance` maybe it could be `tmax = 1000` (variable which is currently [unused](https://github.com/KhronosGroup/Vulkan-Samples/pull/473/files#diff-458b20d617252a9a8c02d63fdf59dec32e54f5c6b5472ef7407655d21674965fR88))

**Comment by KonstantinSeurer** [comment]
There is a section that defines t to be the z coordinate in ray space divided by the length of the unnormalized ray direction vector. So if we want to trace from some world_pos to some light_pos and out direction is light_pos - world_pos, tmax has to be one since the value of t for light_pos would be 1.

**Comment by gpx1000** [comment]
Good catch on this.  Jose is right that the first hit usage means it's not really need to track tmax.  However, I wonder if it would be clearer and thus a better sample if we did switch tmax to be what's used here and delete distance?  Setting tmax to 1.0 seems to be correct too.

**Comment by KonstantinSeurer** [comment]
The point is that we either need to normalize the direction vector and set tmax to distance or keep the direction vector the way it currently is and set tmax to 1.0. I is correct that we do not care about t because we are using `gl_RayFlagsTerminateOnFirstHitEXT` but we need tmax to be correct in order to discard any potential intersection past the light.

**Comment by JoseEmilio-ARM** [comment]
Yes sorry, got confused, this is a positional light so we need a shorter `tmax`. Happy with either solution, did you have a chance to test it on a couple of platforms?

**Comment by KonstantinSeurer** [comment]
Setting `tmax` to 1 is probably the more elegant/optimal solution as it avoids calculating the length. I only tested it on AMD with RADV and I don't have a ray tracing capable Nvidia GPU.

**Review by SaschaWillems — APPROVED** [review]
LGTM and works fine on Windows 10 with my NV RTX 2060.

**Review by gpx1000 — APPROVED** [review]

**Pull request merged**
