### PR TITLE
docs: improve "-j" parameter in build instructions

### PR DESCRIPTION
**Pull request by grische**
## Description

As CMake 3.16 is the minium required version, use "-j" of CMake. 
Also replace hardcoded "-j4" with "-j$(nproc)" to speed up building on more powerful systems.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

### CODE REVIEW

**Comment by SaschaWillems** [comment]
Thank you very much for your PR. Can you also update the copyright headers in the file(s) you changed? This is a requirement as otherwise CI will fail.

**Comment by marty-johnson59** [comment]
Hi @grische, we're unable to merge this until the copyright header is updated to 2023.  Can you make that change?  Thx.

**Comment by grische** [comment]
Thank you @SaschaWillems ! I didn't come around looking into this yet.

**Review by tomadamatkinson — APPROVED** [review]
Checks look like they are throwing false positives. This is safe to merge

**Pull request merged**
