### PR TITLE
Unifying approach for C- and C++-bindings, on DebugUtils classes.

### PR DESCRIPTION
**Pull request by asuessenbach**
## Description

This is a proposal how we could unify the C- and the C++-bindings of Vulkan in the framework classes: Replace the two classes HPPFoo and Foo by one class Foo, that provides interfaces for both bindings.
Pro:
- reduced class count
- no parallel class hierarchy handling
- can be rolled in on a class-by-class basis

Contra:
- more complex interface of those classes.

Build tested on Win10 with VS2022. Run tested on Win10 with NVidia GPU.

Note, that this change will not run with the non-hpp samples, as there's no dispatcher initialization done for them. It's just for demonstration purposes, how unifying C- and C++-bindings could look like.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#General-Requirements)

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](./../samples/extensions/conditional_rendering)
- [ ] For new samples, I have added a link to the [Antora navigation](./../antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

### CODE REVIEW

**Comment by asuessenbach** [comment]
Has anybody an idea what problem "Build Ubuntu with Direct To Display" has with template typename called "B0"?
This probably hasn't changed for a while but fails right now?? It seems, there's some define out there in the wild, making some numeric constant out of "B0"...

I can easily change that name in VulkanHppGenerator to something more meaningful, but it would take a while 'til it's in an official SDK.

**Comment by tomadamatkinson** [comment]
> Replace the two classes HPPFoo and Foo by one class Foo, that provides interfaces for both bindings.

I am all for this. I think this would help dramatically! Ill make sure i find time to review this properly

**Review by tomadamatkinson — COMMENTED** [review]
Am i right in saying this is similar to the approach of C++ facades over C code. But now the implementation is Vulkan HPP and the facade is C?

**Comment by marty-johnson59** [comment]
This will be resolved - see PR910

**Pull request closed without merging**
